import sys, json; sys.path.insert(0,"docs/tooling/_scratch")
from dwg import *
EID="9d4820fb3a9bbf9308cd5da8"
c._request("DELETE", f"/api/v6/elements/d/{D}/w/{W}/e/570f2241d169500f50288030")
v=views(EID)["items"][0]; VID=v["viewId"]
g=geometry(EID,VID)
SC, CX, CY, OX = 1/5, 200.0, 190.0, 895.0     # sheet mm: centre of view at (200, 190); model centre x ~ 895
def sheet(x_mm, y_mm): return [CX + (x_mm - OX) * SC, CY + y_mm * SC, 0]
lines={}
for x in g["bodyData"]:
    if x["type"]=="line" and x["deterministicId"][:2] in ("RK","RN","RO","RP","RQ","RR"):
        lines[x["deterministicId"][:2]]=x
def ref(x, which, snap):
    return {"coordinate":x["data"][which] if which!="mid" else [(a+b)/2 for a,b in zip(x["data"]["start"],x["data"]["end"])],
            "type":"Onshape::Reference::Point","uniqueId":x["uniqueId"],"viewId":VID,"snapPointType":snap}
fmt={"dimdec":1,"type":"Onshape::Formatting::Dimension"}
anns=[]
names={"RN":"Q_1","RO":"Q_2","RP":"Q_3","RQ":"Q_4","RR":"Q_5"}
for k,(key,nm) in enumerate(names.items()):
    L=lines[key]; xm=L["data"]["start"][0]*1000; half=abs(L["data"]["start"][1])*1000
    # width across the station line, text just below the ski
    anns.append({"type":"Onshape::Dimension::PointToPoint","pointToPointDimension":{
        "point1":ref(L,"start","ModeStart"),"point2":ref(L,"end","ModeEnd"),
        "textPosition":{"coordinate":sheet(xm + 45, 0),"type":"Onshape::Reference::Point"},"formatting":fmt}})
    # position from the TAIL end (datum at x = 0): midpoint to midpoint, both on y = 0
    anns.append({"type":"Onshape::Dimension::PointToPoint","pointToPointDimension":{
        "point1":ref(lines["RK"],"mid","ModeMid"),"point2":ref(L,"mid","ModeMid"),
        "textPosition":{"coordinate":[CX + (xm/2 - OX) * SC, CY + 22 + 8 * k, 0],"type":"Onshape::Reference::Point"},"formatting":fmt}})
anns.append({"type":"Onshape::Note","note":{"position":{"coordinate":[20, 280, 0],"type":"Onshape::Reference::Point"},
    "contents":"4101 PLAN -- generated by Station geometry (publish_tools). Station lines + datum come from the model, not a sketch.","textHeight":3.5}})
s=modify(EID,[{"messageName":"onshapeCreateAnnotations","formatVersion":"2021-01-01","annotations":anns}],"4101 station dimensions")
print(s.get("output")[:600])
