"""Writes the Mutual Trim+, Offset+ and Thicken+ deck specs (docs/decks/<slug>/spec.json). Run from the repo root.
Kept as a script so the shared pieces (the flip-vs-reference slide, the orientation tip, the reference rows) stay in
step across the reference-side decks; edit here, re-run, rebuild. See docs/decks/DECK_NOTES.md.
"""
import json


def common_ref(tab, tests, sec):
    return [
        ["Document", "Reference_Side_Features (22764764a00a7f607dbc1c4d)"],
        ["Tab", tab + "  (uses reference_side_utils)"],
        ["Tests", "Reference side tests studio: " + tests + "  -  devtools/onshape/check_reference_side_tests.py (34/34)"],
        ["Examples", "topsheet_surf studio (the user's derive of Design_Master topsheet and sidewall bodies)"],
        ["Explainer", "docs/explainers/reference_side/reference_side_explained.md, section " + sec],
        ["Related", "Split+, Mutual Trim+, Offset+, Thicken+, Orient to reference (same reference rule); Extract variables"]]


ORIENT_TIP = {"kind": "limit", "head": "Outputs keep their input's orientation",
              "body": "The reference picks the side, not the normal. Built-ins downstream that follow the normal (Thicken, Offset "
                      "surface, Move face) need Orient to reference first -- or use the reference-side feature instead."}

WHY_FLIP = {"type": "concept", "title": "Why a reference instead of a flip",
            "image": "docs/explainers/reference_side/img/fig01_flip_vs_reference.png",
            "points": [{"head": "A flip is about a normal", "body": "'Front', 'opposite direction', 'Thickness 1' all mean: relative to the normal -- and normals change freely upstream."},
                       {"head": "A reference is about the model", "body": "Pick geometry on the side you mean. The choice survives any change of orientation."},
                       {"head": "Drop-in", "body": "With no reference, the feature behaves exactly like the built-in."}]}

MT = {"slug": "mutual_trim_plus", "title": "Mutual Trim+",
      "tagline": "Onshape's mutual trim, with the side to keep on each surface named by a reference instead of by a flip -- so the trim keeps the right corner whatever the surfaces' orientations.",
      "document": "Reference_Side_Features", "icon": "icons/final/mutual_trim_plus_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Two surfaces trim each other along their intersection and each keeps one side. The built-in picks that side with a 'keep opposite side' box per surface, tied to each surface's normal -- which flips when a loft, offset or mirror upstream changes. Mutual Trim+ keeps, on each surface, the side a reference is on.",
           "useWhen": ["Two surfaces meet at a corner you want to keep (a top and a wall)", "Either surface's orientation may change upstream", "A fillet or thicken will follow the trim edge"],
           "image": "docs/decks/mutual_trim_plus/shots/hero.png", "caption": "Mutual Trim+ open on the ski: unfilleted top x SW rout wall."},
          WHY_FLIP,
          {"type": "concept", "title": "How each side is decided",
           "image": "docs/explainers/reference_side/img/fig04_mutual_trim.png",
           "points": [{"head": "Against the OTHER surface", "body": "Each surface is cut in two by the other one. The side kept is the one on the reference's side of that other surface (signed distance)."},
                      {"head": "Not by nearness", "body": "On a leaning wall the nearest piece can be the wrong one (right). Distance is only a fallback when the pieces do not straddle the other surface."},
                      {"head": "Per surface", "body": "Each surface has its own 'keep side nearest reference' arrow: on = the reference's side, off = the other side."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/mutual_trim_plus/shots/dialog.png",
           "positions": {"Keep side nearest reference (first)": [0.93, 0.203, "right"], "Keep side nearest reference (second)": [0.93, 0.386, "right"]},
           "params": [["First surface", "One surface body."],
                      ["Keep side nearest reference (first)", "The arrow by the first surface. On: keep its side nearer the reference (the inside). Off: the farther side."],
                      ["Second surface", "The other surface body."],
                      ["Keep side nearest reference (second)", "The same for the second surface."],
                      ["Keep side reference", "Geometry on the keep side of BOTH surfaces -- best a mate connector or vertex in the corner you keep. Empty = the built-in."],
                      ["Merge", "Union the two trimmed surfaces into one body (default on)."],
                      ["Debug", "Print side distances: which side each surface kept, and whether by side (normal case) or by distance (fallback)."]]},
          {"type": "example", "title": "Example: top x sidewall rout",
           "image": "docs/decks/mutual_trim_plus/shots/section.png",
           "head": "Unfilleted_Top_Surf trimmed with SW_Rout, reference Better_Ref, merged (topsheet_surf studio)",
           "body": "Each surface keeps the part on the reference's side of the other: the top keeps its inside (green), the rout wall keeps the part below the top (blue). The published trimEdges (magenta) is the intersection along which the two were trimmed -- the edge a fillet wants."},
          {"type": "example", "title": "Example: the whole trim edge",
           "image": "docs/decks/mutual_trim_plus/shots/plan.png",
           "head": "The same result from above: keptFaces1 (green) and the trim edge all round the ski (magenta)",
           "body": "keptFaces1 / keptFaces2 tell the two surfaces apart even after Merge makes them one body, so a later feature can offset or thicken just the top, or just the wall."},
          {"type": "outputs",
           "keys": [["output", "The trimmed surfaces (one body when merged)."],
                    ["trimEdges", "The intersection edges the trim left -- where to fillet. Tracked through the merge."],
                    ["keptFaces1", "The faces the first surface kept (still told apart after the merge)."],
                    ["keptFaces2", "The faces the second surface kept."],
                    ["trimEdgeCount", "How many trim edges."]],
           "messages": [["Info", "boolean union no-op", "The surfaces do not intersect; nothing was trimmed."],
                        ["Error", "The keep side reference cannot be placed on either side of the first/second surface",
                         "The pieces do not straddle the other surface and the reference is equally far from both. Pick a closer reference inside the corner to keep."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Put the reference in the corner you keep", "body": "A mate connector just inside the kept corner (e.g. at MRS) -- not a far plane: a far plane's closest point can land at the tip, where the surfaces have turned."},
              {"kind": "tip", "head": "Fillet along trimEdges", "body": "Publish trimEdges with Extract variables; it survives upstream edits that renumber edges."},
              ORIENT_TIP,
              {"kind": "limit", "head": "One orientation after Merge", "body": "Merged, the two halves are one body with one orientation."}]},
          {"type": "reference", "rows": common_ref("mutual_trim_plus", "M1-M2", "2.1")}]}

OP = {"slug": "offset_plus", "title": "Offset+",
      "tagline": "Offset surfaces, or curves, toward the side a reference is on -- surfaces of opposite orientation all move the same way, and curves offset in the frame you choose.",
      "document": "Reference_Side_Features", "icon": "icons/final/offset_plus_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "The built-in offset surface goes along the normal, and the built-in offset curve works in a sketch plane with a flip. Offset+ offsets each surface body toward the reference's side of it, and offsets 3D curves in a transport, surface-normal or plane frame -- toward the reference too.",
           "useWhen": ["Surfaces from different sources face different ways", "A 3D edge chain needs a constant offset (along a surface, lifted off it, or in plan)", "Corners of the chain must be rounded or trimmed cleanly"],
           "image": "docs/decks/offset_plus/shots/hero.png", "caption": "Offset+ open on the ski topsheet: offset 2 mm toward the plane 'Below ski'."},
          WHY_FLIP,
          {"type": "concept", "title": "Curve frames and corners",
           "image": "docs/explainers/reference_side/img/fig05_offset_curves.png",
           "points": [{"head": "Transport frame", "body": "The direction is carried along the chain without twisting -- a helix offset 'toward the axis' stays inside (test C7)."},
                      {"head": "Surface normal / plane", "body": "Off a surface, along it, or in the plane perpendicular to a direction (plan view)."},
                      {"head": "Corners", "body": "A gap on the outside gets an arc (radius = the distance); an overlap on the inside is trimmed to the crossing (test C8)."}]},
          {"type": "dialogshot", "title": "The dialog: surfaces", "screenshot": "docs/decks/offset_plus/shots/dialog_surface.png",
           "positions": {"Offset toward reference": [0.93, 0.679, "right"]},
           "params": [["Offset type", "SURFACE: offset surface bodies. CURVE: offset edges or wires (next slides)."],
                      ["Faces and surfaces to offset", "Each body is offset toward the reference's side of THAT body."],
                      ["Distance", "Offset distance."],
                      ["Side reference", "Geometry on the side to offset toward. Empty = the arrow alone (a plain flip)."],
                      ["Offset toward reference", "The arrow. On: toward the reference. Off: away from it."],
                      ["Debug", "Print details: which way each body or chain went, corners and fits."]]},
          {"type": "dialogshot", "title": "The dialog: curves, plane frame", "screenshot": "docs/decks/offset_plus/shots/dialog_plane.png",
           "positions": {"Frame": [0.02, 0.363], "Offset toward reference": [0.93, 0.652, "right"]},
           "params": [["Offset type", "CURVE."],
                      ["Curves and edges to offset", "Connected edges form one chain; each chain becomes one wire."],
                      ["Frame", "Transport frame (default) / Surface normal / Plane."],
                      ["Plane normal", "Plane frame: the offset lies in planes perpendicular to this. Empty = world Z (a plan-view offset)."],
                      ["Distance", "Offset distance."],
                      ["Side reference", "Here the Front plane: every chain moves toward it."],
                      ["Offset toward reference", "The arrow: toward / away."],
                      ["Fit", "Samples per edge (24), Max station spacing (5 mm), Fit tolerance (0.001 mm)."]]},
          {"type": "dialogshot", "title": "The dialog: curves, surface-normal frame", "screenshot": "docs/decks/offset_plus/shots/dialog_surfaceframe.png",
           "positions": {"Frame": [0.02, 0.322], "Surface": [0.02, 0.43]},
           "params": [["Frame", "Surface normal: the direction comes from a surface at each point."],
                      ["Surface", "The surface whose normals define the offset (its orientation does not matter: normals are kept continuous)."],
                      ["Direction", "Along surface normal: lift the curve off the surface. Along surface: stay in it, perpendicular to the curve."]],
           "note": "On the topsheet edge chain all three frames land at y 70 (5 mm in): the topsheet is flat across its width there. They differ on twisted chains and curved surfaces (tests C5-C7)."},
          {"type": "example", "title": "Example: surface offset",
           "image": "docs/decks/offset_plus/shots/surface_section.png",
           "head": "Topsheet offset 2 mm toward 'Below ski' (topsheet_surf studio)",
           "body": "The topsheet faces down, into the ski. Offset+ reads which side of the topsheet 'Below ski' is on and offsets that way -- if the topsheet's normal flipped upstream, the offset would still go down. The offset surface keeps the topsheet's orientation (still facing down)."},
          {"type": "outputs",
           "keys": [["output", "The offset surfaces or wires."],
                    ["startVertex / endVertex", "Curves: the ends of each wire (start = the end at the source's start)."],
                    ["startEdge / endEdge", "Curves: the edge at each end."],
                    ["cornerArcs", "Curves: the arcs that round the outside corners."],
                    ["boundaryEdges", "Surfaces: the open boundary edges of the offset surfaces."]],
           "messages": [["Info", "Corners: N rounded, M trimmed.", "The corner counts are reported here only (not published)."],
                        ["Warning", "N corner(s) could not be closed ... The wire has a gap at each.", "A corner sharper than the offset allows, or skew 3D pieces. Reduce the distance or split the chain there."],
                        ["Error", "The side reference is not to either side of chain k in this frame", "The reference lies along the curve or on the surface. Move it off to one side."],
                        ["Error", "The curve runs along the plane / surface normal", "No offset direction exists there in that frame."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Use a local reference", "body": "A mate connector or vertex near the geometry, on the side meant."},
              {"kind": "tip", "head": "Transport for 3D chains", "body": "It never flips at an inflection and never twists, so the offset stays on the side it started."},
              ORIENT_TIP,
              {"kind": "limit", "head": "Sharp corners and large distances", "body": "Where the offsets neither separate nor cross cleanly the corner is left open, with a warning."}]},
          {"type": "reference", "rows": common_ref("offset_plus", "O1-O2 (surfaces), C1-C8 (curves)", "2.3")}]}

TH = {"slug": "thicken_plus", "title": "Thicken+",
      "tagline": "Onshape's Thicken, with the two thicknesses named 'toward reference' and 'away from reference' instead of by the face normal -- the boolean step unchanged.",
      "document": "Reference_Side_Features", "icon": "icons/final/thicken_plus_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "The built-in Thicken's Thickness 1 goes along the face normal, so the same feature thickens outward on one model and inward on another. Thicken+ decides per surface body which way is 'toward the reference' and puts the Toward thickness there. Everything else -- New / Add / Remove / Intersect, merge scope -- is the built-in.",
           "useWhen": ["Surfaces of mixed orientation must thicken the same way", "A surface's normal may flip upstream", "You want a clear error where a thicken would fold, with its location"],
           "image": "docs/explainers/reference_side/img/fig06_thicken.png", "caption": "Left: both sheets thicken toward the reference whatever their normals. Right: the curvature check."},
          WHY_FLIP,
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/thicken_plus/shots/dialog.png",
           "positions": {"Swap sides": [0.93, 0.693, "right"]},
           "params": [["Creation type", "New / Add / Remove / Intersect -- the built-in boolean step, unchanged."],
                      ["Faces and surfaces to thicken", "Surfaces or faces; each owner body is thickened on its own side."],
                      ["Side reference", "Geometry on the side to thicken toward -- best a mate connector or vertex near the surface. Empty = along the normals."],
                      ["Toward reference", "Thickness on the reference's side."],
                      ["Away from reference", "Thickness on the other side."],
                      ["Swap sides", "The arrow: exchange the two thicknesses."],
                      ["Keep tools", "Keep the input surfaces."],
                      ["Advanced", "Check curvature (on): report where a concave radius is smaller than the thickness. Print details."]]},
          {"type": "example", "title": "Example: opposite normals, same result",
           "image": "docs/decks/thicken_plus/shots/t2_section.png",
           "head": "Test T2: sheets at z +50 and -50 with opposite normals, reference at the centre, Toward 2, Away 3",
           "body": "Both sheets put 2 mm toward the centre and 3 mm away: top z 48..53, bottom z -53..-48 -- mirror images, although their normals point opposite ways. T3 (Swap sides) gives 47..52 / -52..-47. T6: Add into a cube, 5 mm up -> one part, volume 1 018 000 mm3."},
          {"type": "concept", "title": "The curvature check",
           "image": "docs/explainers/reference_side/img/fig06_thicken.png",
           "points": [{"head": "Why thickens fail", "body": "Thickening toward a concave side by more than its radius turns the offset inside out."},
                      {"head": "Found before the kernel fails", "body": "Each face is sampled on a 9 x 9 grid; the first place that would fold is marked red, with its radius."},
                      {"head": "Tests T4 / T5", "body": "Half cylinder r 10 thickened toward its axis: 15 mm -> the error with location; 5 mm -> a clean shell."}]},
          {"type": "outputs",
           "keys": [["output", "The thickened bodies (or the parts they merged into)."],
                    ["towardFaces", "The faces on the reference's side (at the Toward thickness)."],
                    ["awayFaces", "The faces on the other side (on the input surface when Away is 0)."],
                    ["sideFaces", "The faces around the edges of the thickened surfaces."]],
           "messages": [["Error", "Both thicknesses are zero.", ""],
                        ["Error", "The side reference lies on surface k", "Move the reference off the surface."],
                        ["Error", "Surface k is concave with radius r mm at (x, y, z) ... the thicken would fold there.", "Reduce that side's thickness below r, or swap sides. The red point marks the place."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Use it instead of Thicken downstream", "body": "Surfaces from Split+, Mutual Trim+ or Offset+ keep their inputs' orientation; Thicken+ does not care which way they face."},
              {"kind": "tip", "head": "Faces stay named through the boolean", "body": "towardFaces / awayFaces / sideFaces still resolve after Add merges the result into a part."},
              {"kind": "limit", "head": "Orientation does not apply", "body": "Its outputs are solids, which always face outward -- Orient to reference is for surfaces."}]},
          {"type": "reference", "rows": common_ref("thicken_plus", "T1-T6 (T4 must error)", "2.4")}]}

for spec in (MT, OP, TH):
    json.dump(spec, open("docs/decks/%s/spec.json" % spec["slug"], "w"), indent=2)
    print("wrote docs/decks/%s/spec.json" % spec["slug"])
