"""Writes the Curve tools deck specs (Clean wire, Map curve, Merge curve, Evaluate profiles, Fillet wire).
Run from the repo root; then build each with docs/tooling/build_deck.js. See docs/decks/DECK_NOTES.md.
"""
import json

EXPL = "docs/explainers/curve_tools/"


def ref(tab, tests, sec, examples="Test_1 studio"):
    return [["Document", "Curve_tools (2143812a99089658c704f0bc)"],
            ["Tab", tab + "  (uses curve_core)"],
            ["Tests", tests],
            ["Examples", examples],
            ["Explainer", "docs/explainers/curve_tools/curve_tools_explained.md, section " + sec],
            ["Related", "Clean wire, Map curve, Merge curve, Evaluate profiles, Fillet wire; Extract variables"]]


ENDS = [["startVertex / endVertex", "The ends of the result (start = the tail end: arc length grows with world X)."],
        ["startEdge / endEdge", "The edge at each end."]]

CW = {"slug": "clean_wire", "title": "Clean wire",
      "tagline": "Rebuild a messy model-made wire with fewer edges and control points: tangent stretches become one spline each, real corners stay corners, lines and arcs pass through exactly.",
      "document": "Curve_tools", "icon": "icons/final/clean_wire_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Model-made wires come out correct but messy: slivers a tenth of a millimetre long, 0.4 deg kinks, heavy rational splines -- and lofts and fills through them wiggle or fail. Native Approximate samples 200 fixed points and ignores corners. Clean wire rebuilds the wire run by run.",
           "useWhen": ["A wire feeds a loft, fill or driven offset", "It has slivers or near-tangent kinks", "You want a lighter curve that stays within 0.01 mm"],
           "image": "docs/decks/clean_wire/shots/after.png", "caption": "SW_SHELF after Clean wire (Auto): 13 runs, max deviation 0.009 mm."},
          {"type": "concept", "title": "How each joint is read",
           "image": EXPL + "img/fig01_joints_slivers.png",
           "points": [{"head": "Tangent, near, corner", "body": "Under 0.57 deg: merged. Under the corner angle (3 deg): merged if 'make tangent' is on. Larger: a corner, kept."},
                      {"head": "Slivers (< 0.5 mm)", "body": "Judged by their own two joints: absorbed next to a tangent joint, kept as a chamfer between two corners."},
                      {"head": "Lines and arcs", "body": "A real line or arc passes through unchanged; arcs stay sketch arcs, so Onshape shows their radius."}]},
          {"type": "concept", "title": "Samples where the curve bends",
           "image": EXPL + "img/fig02_adaptive_sampling.png",
           "points": [{"head": "Spacing from the tolerance", "body": "s = sqrt(4 tol / kappa): the chord between samples misses the curve by half the tolerance."},
                      {"head": "No edge skipped", "body": "3 to 200 samples per edge, 0.05 to 10 mm apart -- a sliver still gets its samples."},
                      {"head": "Exact end tangents", "body": "Each fit starts and ends on the true tangent, so runs join smoothly."}]},
          {"type": "dialogshot", "title": "The dialog (Auto)", "screenshot": "docs/decks/clean_wire/shots/dialog.png",
           "params": [["Mode", "AUTO: runs made from the joints. MANUAL: you group edges yourself (Auto-populate fills the groups)."],
                      ["Wire", "A wire body or the edges of one open chain."],
                      ["Name", "Names the result."],
                      ["Runs", "Read-only: each run's edges, exact copy or fit, control points, deviation."],
                      ["Corner angle", "Joints turning more than this are corners (3 deg keeps the ski's ramp creases)."],
                      ["Make nearly tangent joints tangent", "Merge joints between 0.57 deg and the corner angle."],
                      ["Sliver length", "Edges shorter than this are judged as slivers (0.5 mm)."],
                      ["Fit control points to tolerance", "Button: fit every run with no cap; set the maximum to what the largest run needed."],
                      ["Approximation parameters", "Degree 3, tolerance 0.01 mm, maximum 30 control points."],
                      ["Maximum deviation", "Read-only: the result's largest distance from the source."],
                      ["Show deviation", "Draw that deviation as a comb."],
                      ["Show runs", "Colour the runs in the view."],
                      ["Delete input wire", "Remove the source wire (whole wire bodies only)."],
                      ["Projection", "Also clean the plan view: the 3D wire is dropped onto a wall over the cleaned plan."],
                      ["Reduction", "Read-only: control points and edges before / after."],
                      ["Debug", "Joints, runs, corners, control polygons."]]},
          {"type": "example", "title": "Example: before",
           "image": "docs/decks/clean_wire/shots/before.png",
           "head": "The SW_SHELF wire as the model makes it: 17 edges (plan view, ticks at the joints)",
           "body": "Several short pieces and near-tangent joints -- each a place a loft or offset can wiggle."},
          {"type": "example", "title": "Example: after",
           "image": "docs/decks/clean_wire/shots/after.png",
           "head": "Clean wire (Auto), default settings: 13 runs, max deviation 0.009 mm",
           "body": "Tangent stretches refitted as one spline each, the real corners kept, lines and arcs copied exactly."},
          {"type": "outputs",
           "keys": ENDS + [["breakVertices", "The vertices between runs (the corners kept)."]],
           "messages": [["Warning", "Short of tolerance: ...", "A run misses the source by more than the tolerance: raise its control points, or split it."],
                        ["Info", "N edge(s) -> M; K corner(s) inside a group were fitted through", "Manual mode."],
                        ["Warning", "...came out as N bodies instead of one", "A joint did not close; the gaps are listed."],
                        ["Error", "Closed loops are not supported / not one chain", "Pick one open chain."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Start with Auto", "body": "Check the Runs list; switch to Manual (Auto-populate) only to override a run."},
              {"kind": "tip", "head": "Reference the body or its keys", "body": "Never the result's edge ids: they change whenever a run changes."},
              {"kind": "limit", "head": "Open chains only", "body": "Closed loops are refused."},
              {"kind": "limit", "head": "Manual groups go stale", "body": "They point at the source's edges; after an upstream renumbering, Auto-populate again."}]},
          {"type": "reference", "rows": ref("clean_wire", "Tests studio (curve_tools_tests: ends, runs in order)", "2.1")}]}

MC = {"slug": "map_curve", "title": "Map curve",
      "tagline": "Carry a span from one chain onto another by arc length from a reference point: s mm along the first from its zero lands s mm along the second from its zero.",
      "document": "Curve_tools", "icon": "icons/final/map_curve_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "The same stations are needed on different curves of a ski -- the RSL, the side profile, the core bottom -- measured along each curve from the same place (the FCP). Trim and split work by position, not by distance along the curve. Map curve measures along both chains from a zero point.",
           "useWhen": ["A span defined on one curve is needed on another", "Distances must follow the curve, not X", "Arcs must stay arcs (Trim mode never refits)"],
           "image": "docs/decks/map_curve/shots/result.png", "caption": "SKI_PROFILE trimmed to the RSL span, measured along it from the FCP."},
          {"type": "concept", "title": "Arc length from a zero point",
           "image": EXPL + "img/fig03_map_arc_length.png",
           "points": [{"head": "Same distance along each", "body": "The from-chain's span [start, end], measured from its zero, is laid onto the to-chain from its zero."},
                      {"head": "World X or closest", "body": "World X: the zero lands where each chain crosses the point's X. Closest point: the nearest point on each chain."},
                      {"head": "Direction check", "body": "If the chains run opposite ways at the zero, the feature stops and asks for Flip to-chain."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/map_curve/shots/dialog.png",
           "positions": {"Mode": [0.02, 0.17], "Reference point": [0.02, 0.55], "Projection": [0.02, 0.756], "Flip to-chain": [0.93, 0.756, "right"]},
           "params": [["Mode", "Deform from-edges onto to-edges / TRIM to-edges to the from span / Deform and merge to one curve."],
                      ["From edges", "The chain that sets the span."],
                      ["To edges", "The chain the span lands on (never modified)."],
                      ["Reference point", "SHARED: one zero point for both. SEPARATE: a zero for each chain."],
                      ["Zero point", "A mate connector or vertex (e.g. the FCP)."],
                      ["Projection", "WORLD X (default) or CLOSEST POINT: how the zero lands on each chain."],
                      ["Flip to-chain", "The arrow: when the two chains run opposite ways at the zero."],
                      ["Name", "Names the result."],
                      ["Debug", "Chain ends (green start, red end) and a summary."]]},
          {"type": "example", "title": "Example: trim to the RSL span",
           "image": "docs/decks/map_curve/shots/result.png",
           "head": "SKI_PROFILE (grey) trimmed to the span of RSL_Wire (orange), zero at the FCP vertex -- result in blue",
           "body": "Trim mode copies the to-edges and cuts them exactly at the two arc lengths; nothing is refitted, so the profile's arcs stay arcs."},
          {"type": "outputs",
           "keys": ENDS + [["spanStart / spanEnd", "The from-chain's span, measured from its zero."],
                           ["toStart / toEnd", "Where that span lands on the to-chain."],
                           ["stationCount", "Samples used (Deform modes)."]],
           "messages": [["Error", "chains point in opposite directions ... Tick Flip to-chain", ""],
                        ["Error", "from-edges run X mm past the start / end of the to-edges", "The to-chain is too short for the span."],
                        ["Info", "do not span the zero point's X; closest point used", "World X fell back to Closest point."],
                        ["Info", "Merged result is a spline; arc radius not preserved", "Deform and merge mode."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Use Trim for exact results", "body": "It cuts the original edges; lines and arcs keep their type."},
              {"kind": "limit", "head": "Deform modes are phase 1", "body": "They give the to-chain over the from span, resampled and refitted; carrying geometry that lies off the from-chain is not built yet."}]},
          {"type": "reference", "rows": ref("map_curve", "Tests studio (curve_tools_tests: trim to-edges, ends)", "2.2")}]}

MG = {"slug": "merge_curve", "title": "Merge curve",
      "tagline": "Absorb one edge into its neighbour as a single fitted spline -- Edit curve / Composite + Approximate in one step -- and keep the right body.",
      "document": "Curve_tools", "icon": "icons/final/merge_curve_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "A short edge next to a long one (a tip section, a sliver left by a split) wants to be part of it. Onshape has no join; every route is fit-then-replace, and doing it by hand loses the wire's identity. Merge curve fits the two edges as one spline and puts it back where it belongs.",
           "useWhen": ["Two edges of a wire should be one smooth curve", "The wire's name and identity must survive", "The ends must still meet their neighbours exactly"],
           "image": "docs/decks/merge_curve/shots/result.png", "caption": "The RD baseline after merging its tip section: 2 edges left."},
          {"type": "concept", "title": "Which body survives",
           "image": EXPL + "img/fig04_merge_outcomes.png",
           "points": [{"head": "In place", "body": "The seed is its wire's only edge: the wire is edited and keeps its id and name."},
                      {"head": "Rebuild", "body": "The wire has other edges: they and the merged curve become a new wire (info notice)."},
                      {"head": "Extract", "body": "The seed is not on a wire: the fitted spline is the output."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/merge_curve/shots/dialog.png",
           "params": [["Seed edge", "The edge that is edited."],
                      ["Merge edge", "The edge absorbed; it must meet the seed end to end."],
                      ["Keep start derivative", "Keep the seed's own start tangent (on)."],
                      ["Keep end derivative", "Keep the merge edge's own end tangent (on)."],
                      ["Approximation", "Degree, tolerance, maximum 100 control points."],
                      ["Output name", "Pre-filled with the seed wire's name."],
                      ["Note arc loss", "Say so when a line or arc becomes a spline."],
                      ["Debug", "Print diagnostics."]]},
          {"type": "example", "title": "Example: the RD baseline tip",
           "image": "docs/decks/merge_curve/shots/result.png",
           "head": "The baseline's tip section merged into its main edge (the merged edge in blue)",
           "body": "The seed wire had other edges, so it was rebuilt: the untouched edge and the merged curve form the new wire, the ends snapped to their neighbours so it still chains."},
          {"type": "outputs",
           "keys": ENDS + [["mergedEdge", "The merged curve's edge."], ["degree / controlPointCount", "Of the fitted spline."]],
           "messages": [["Info", "Rebuilt the seed wire ... original body was replaced", "The Rebuild case."],
                        ["Info", "arc radius not preserved", "A line or arc became a spline."],
                        ["Error", "not G0 connected", "The two edges do not meet end to end."]]},
          {"type": "tips", "items": [
              {"kind": "limit", "head": "Always a spline", "body": "A merged line or arc loses its type."},
              {"kind": "tip", "head": "Many edges?", "body": "To clean a whole wire use Clean wire instead."}]},
          {"type": "reference", "rows": ref("merge_curve", "Tests studio (curve_tools_tests: merge, ends)", "2.3")}]}

EP = {"slug": "evaluate_profiles", "title": "Evaluate profiles",
      "tagline": "Project a chain onto a plane and cut it where it folds back -- or outline a part and split its outline into top, bottom and middle profiles.",
      "document": "Curve_tools", "icon": "icons/final/evaluate_profiles_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Side profiles of a core, a topsheet or a sidewall are needed as clean curves: for fills, for drawings, for measuring. Native Project and Outline give an undivided loop, with slivers, that can fold back at the tip. Evaluate profiles gives the profiles you actually want, named.",
           "useWhen": ["You need a part's top / bottom / middle side profile", "A projected chain folds back at a tip", "An outline has micro-edges that break a fill"],
           "image": "docs/decks/evaluate_profiles/shots/p1.png", "caption": "P1: a crowned sheet outlined: top, middle and bottom profiles."},
          {"type": "concept", "title": "Two jobs",
           "image": EXPL + "img/fig05_evaluate_profiles.png",
           "points": [{"head": "Edges", "body": "Project, then cut where the chain stops advancing along the prevailing direction (400-sample scan, then bisection)."},
                      {"head": "Part", "body": "The two longest runs along the direction are top and bottom (top = higher); the middle is their average at matching stations."},
                      {"head": "Micro-edges merged", "body": "Outline edges under 0.01 mm are merged away -- a 1.7 um edge once broke a fill."}]},
          {"type": "dialogshot", "title": "The dialog: Part", "screenshot": "docs/decks/evaluate_profiles/shots/dialog_part.png",
           "params": [["Profile from", "EDGES: project a chain. PART: outline a solid or surface."],
                      ["Name", "Part outputs are named <name> top, <name> bottom, ..."],
                      ["Part or surface to outline", "A solid or surface body, or a face of one."],
                      ["Return", "Top / Bottom / Middle / Periphery / All profiles / Full (profiles + connectors)."],
                      ["Merge edges shorter than", "0.01 mm; 0 = off."],
                      ["Project onto", "A planar face."],
                      ["Prevailing direction", "The direction profiles run along (+ flip). Default: the longest in-plane extent."],
                      ["Output", "One curve / One per input curve (exact) / Efficient (merges where exact)."],
                      ["Approximation", "60 samples, degree 3, 0.01 mm, 24 control points."],
                      ["Debug", "Scan, curve detail, colour the profiles."]]},
          {"type": "dialogshot", "title": "The dialog: Edges", "screenshot": "docs/decks/evaluate_profiles/shots/dialog_edges.png",
           "params": [["Profile from", "EDGES."],
                      ["Edges to project", "The chain."],
                      ["Project onto", "A planar face."],
                      ["Prevailing direction", "Default: the chain's chord."],
                      ["Output", "One curve / One per input curve / Efficient -- see the examples."]]},
          {"type": "example", "title": "Example: One per input curve",
           "image": "docs/decks/evaluate_profiles/shots/p10.png",
           "head": "P10: lines 0-200-400 (collinear), a line to (700, 700), an R100 hook -- projected onto Top",
           "body": "4 exact edges: the projected edges themselves, the arc cut exactly where it turns back (at (759.55, 835.96))."},
          {"type": "example", "title": "Example: Efficient",
           "image": "docs/decks/evaluate_profiles/shots/p11.png",
           "head": "P11: the same chain, Efficient",
           "body": "3 edges: the two collinear lines merged into one 400 mm line; the slanted line and the R100 arc kept exact. One curve (P9) gives a single fitted spline instead."},
          {"type": "outputs",
           "keys": [["top / bottom / middle", "The named profile wires (empty when not requested)."],
                    ["periphery", "The undivided outline (Return = Periphery)."],
                    ["connectors", "The pieces joining top and bottom (Return = Full)."],
                    ["length", "Length of the retained projection (the periphery for a part)."],
                    ["trimmedStart / trimmedEnd", "Whether the projection was cut at each end."]],
           "messages": [["Error", "Nothing projected / not a single connected chain", ""],
                        ["Error", "...seen edge-on: project its edges instead", "A surface lying in the projection direction has no outline."],
                        ["Error", "does not separate into a top and a bottom profile", "Check the prevailing direction."],
                        ["Info", "Merged N outline edge(s) shorter than ...", "Micro-edges removed; locations listed."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Prefer exact output", "body": "One per input curve or Efficient keep lines and arcs exact; One curve is a fit."},
              {"kind": "limit", "head": "Longest loop only", "body": "An outline with several loops keeps only the longest."}]},
          {"type": "reference", "rows": ref("evaluate_profiles", "Evaluate profiles tests studio: P1-P11 (P3 must error)", "2.4", "Evaluate profiles tests studio")}]}

FW = {"slug": "fillet_wire", "title": "Fillet wire",
      "tagline": "Round the corners of a wire or edge chain: an exact tangent arc Onshape recognises as an arc, or a smooth curvature blend -- picked corner by corner.",
      "document": "Curve_tools", "icon": "icons/final/fillet_wire_icon.svg", "status": "Draft 2026-09-25",
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Onshape can fillet corners in a sketch, but not the corners of a wire. Fillet wire rounds chosen corners of any wire or edge chain -- in 2D or 3D -- and edits a wire body in place, so the untouched parts keep their identity.",
           "useWhen": ["A wire (not a sketch) needs rounded corners", "The fillets must be true arcs with a radius", "A 3D corner needs a smooth (G2) blend"],
           "image": "docs/decks/fillet_wire/shots/w1.png", "caption": "W1: two 90 deg corners filleted r10 (magenta)."},
          {"type": "concept", "title": "Tangent arc or curvature blend",
           "image": EXPL + "img/fig06_fillet_wire.png",
           "points": [{"head": "Tangent", "body": "An exact arc, set back d = r tan(turn / 2), emitted as a sketch arc. Needs the corner to be planar."},
                      {"head": "Curvature", "body": "A G2 blend matching both edges' curvature, sized so its average curvature is 1/r. Works in 3D."},
                      {"head": "In place", "body": "A wire is split at the tangent points and only the corner pieces are replaced."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/fillet_wire/shots/dialog.png",
           "params": [["Curves", "Edges or wire bodies."],
                      ["Continuity", "TANGENT: exact arcs. CURVATURE: G2 blends."],
                      ["Radius", "The fillet radius."],
                      ["Apply to all corners", "Off: only the corners you pick."],
                      ["Corners", "Filled by clicking corner points in the view; each can have its own radius."],
                      ["Join into one wire", "Wire input: rejoin the pieces into one body."],
                      ["Advanced", "Corner angle (0.5 deg), Print corners."]]},
          {"type": "example", "title": "Examples",
           "image": "docs/decks/fillet_wire/shots/w3.png",
           "head": "W3: a line running into an arc, r10 -- the fillet is an exact circle tangent to both",
           "body": "W1: two 90 deg corners, r10 -> one wire 291.416 mm long (300 - 4r + pi r). W4: a 3D corner with Tangent is skipped (not planar); W5: the same corner with Curvature -> a G2 blend, average curvature 0.1 /mm."},
          {"type": "outputs",
           "keys": [["filletEdges", "The fillet edges."], ["cornerCount / filletCount / skippedCount", "Corners found / filleted / not filleted."]],
           "messages": [["Warning", "N corner(s) not filleted: ...", "With the reason: radius too large, no circle touches both edges, not in one plane (use Curvature), edges too short, or fillets overlapping."],
                        ["Info", "N corner(s) found. Click them...", "Nothing picked yet."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Radius shown in Onshape", "body": "Tangent fillets are sketch arcs, so clicking one shows its radius."},
              {"kind": "limit", "head": "Curvature fillets are splines", "body": "They have no single radius."},
              {"kind": "limit", "head": "No end keys yet", "body": "Fillet wire does not publish start / end keys."}]},
          {"type": "reference", "rows": ref("fillet_wire", "Fillet wire tests studio: W1-W6 (devtools/onshape/check_fillet_wire.py)", "2.5", "Fillet wire tests studio")}]}

for spec in (CW, MC, MG, EP, FW):
    json.dump(spec, open("docs/decks/%s/spec.json" % spec["slug"], "w"), indent=2)
    print("wrote", spec["slug"])
