"""Writes the xSection deck specs (EI and Cross Section, Solve GJ, Estimate Stiffness, Estimate Deflection, Generate
baseline, Analyze baseline, Update profile). Run from the repo root; then build each with docs/tooling/build_deck.js.
See docs/decks/DECK_NOTES.md. Figures: docs/explainers/xsection/img (img/src/figs.py).
"""
import json

IMG = "docs/explainers/xsection/img/"
DOC = "xSection (f8deedeb1fbd819a8fa20113), 'Stiffness Tools'"
EXPL = "docs/explainers/xsection/xsection_explained.md, section "
STATUS = "Draft 2026-09-25"
RELATED = "EI and Cross Section, Estimate Stiffness, Estimate Deflection, Generate / Analyze baseline, Update profile"
EI_EDGE = "The EI curve: an edge in the XZ plane, world Z in mm = EI in N m^2 (EI and Cross Section's <name>_EI, a measured or a target curve)."


def ref(tab, tests, sec, examples):
    return [["Document", DOC], ["Tab", tab], ["Tests", tests], ["Examples", examples],
            ["Explainer", EXPL + sec], ["Related", RELATED]]


EI = {"slug": "ei_and_cross_section", "title": "EI and Cross Section",
      "tagline": "Cut the ski's layup at stations and compute, at each, the bending stiffness EI, torsional stiffness GJ, neutral axis and mass -- then the ski's flex numbers and weight.",
      "document": "xSection", "icon": "icons/final/ei_cross_section_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "A ski's flex comes from its layup: every ply's shape and material. EI and Cross Section reads the layup straight from CAD (one solid per ply, each with an Onshape material), looks up the moduli in a CSV table, and gives EI(x), GJ(x), the neutral axis and the flex numbers -- so a design change shows its stiffness effect at once.",
           "useWhen": ["You change a layup, core profile or sidecut", "You need the EI curve for deflection, baseline or profile work", "You compare a design with measured stiffness"],
           "image": "docs/decks/ei_and_cross_section/shots/hero.png", "caption": "ROY_Test: the output curves (EI, GJ ...) above the ski; the info reports repaired outlines."},
          {"type": "concept", "title": "Stations",
           "image": IMG + "fig02_stations.png",
           "points": [{"head": "FCP to ACP", "body": "N stations evenly spaced, one exactly at each contact point (numbered 0 ... N-1)."},
                      {"head": "Tip and tail", "body": "Up to 4 extra each at about the same spacing; the tip's are numbered negative."},
                      {"head": "One cut per body", "body": "Outlines are cleaned (duplicates, micron gaps), triangulated and integrated."}]},
          {"type": "concept", "title": "EI of a laminate",
           "image": IMG + "fig03_laminate_ei.png",
           "points": [{"head": "Each body is a ply", "body": "Area, centroid height above the base, its own I, and its modulus E along the ski."},
                      {"head": "Neutral axis", "body": "The E-weighted centroid; EI is the stiffness about it."},
                      {"head": "E, not Q11", "body": "A narrow ski bends like a beam: Q11 would overstate by ~12 % (wood, Titanal), more for +-45 fabric."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/ei_and_cross_section/shots/dialog.png",
           "params": [["Wire to cross section along", "One wire along the ski (X increasing)."],
                      ["Analysis name", "Prefix for the output curves."],
                      ["FCP", "Front contact point (vertex, planar face or mate connector; X only)."],
                      ["ACP", "Aft contact point. FCP and ACP are optional, but flex numbers need both."],
                      ["Cross section bodies", "The layer solids (composites are unpacked)."],
                      ["Material library", "materialData.csv: name, density, E, nu, Q11 ... Q66."],
                      ["Refresh CSV data", "Button: re-read the table."],
                      ["Number of cross sections", "3-200 (50); with FCP / ACP, this many from FCP to ACP."],
                      ["Bodies & Materials", "Per body: its material must match a CSV name exactly, or choose Ignore / Provide material data."],
                      ["Output Options", "Create composites (slow), language, material and body-detail tables."],
                      ["Debug", "Draw edges / points / mesh of chosen stations and bodies."]]},
          {"type": "example", "title": "Example: ROY_Test, 35 stations",
           "image": IMG + "fig04_roy_results.png",
           "head": "EI peaks at 390 N m^2 under the foot; GJ follows (453); the neutral axis sits near mid-thickness",
           "body": "Summary: 20.7 lb/in and 81.3 mm under 30 kg (variable EI); 16.2 lb/in prismatic. The stations cut 4 bodies with micron gaps, repaired (info)."},
          {"type": "concept", "title": "Flex numbers",
           "image": IMG + "fig05_flex_numbers.png",
           "points": [{"head": "The test", "body": "Simply supported at FCP and ACP, a point load at the mount (MRS)."},
                      {"head": "Prismatic", "body": "P L^3 / (48 EI_avg): the average EI over the span."},
                      {"head": "Variable EI (Mohr)", "body": "P x integral s^2 / EI: the stiff middle counts more -- 20.7 vs 16.2 lb/in on ROY_Test."}]},
          {"type": "outputs", "keysTitle": "Outputs",
           "keys": [["<name>_EI", "EI curve: Z mm = EI N m^2. The input of every other xSection feature."],
                    ["_GJ, _neutralAxis, _linealDensity, _profileHeight", "GJ (mm = N m^2), NA height, mass per length (1 kg/m = 100 mm), thickness (true scale)."],
                    ["CrossSectionAnalysis (attribute)", "Everything per station, read by the Cross-Section Analysis table and Update profile."]],
           "messages": [["Info", "Repaired N body section outline(s)...", "Duplicate edges or micron gaps closed; details on the console."],
                        ["Warning", "N body section(s) between FCP and ACP could not be closed or came out with no area", "EI is low there."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Name materials exactly", "body": "The Onshape material name must match the CSV Name, case and spaces included; otherwise the body is ignored or needs data."},
              {"kind": "tip", "head": "Turn off Create composites", "body": "It is the slowest step and only draws the section wires."},
              {"kind": "limit", "head": "Wood cores", "body": "Some CSV rows (Aspen, Poplar) are isotropic placeholders: EI is fine, their GJ is overstated."},
              {"kind": "limit", "head": "Ends", "body": "Planes grazing the tip or tail can lose a thin outline (console only)."}]},
          {"type": "reference", "rows": ref("xSect (features/xSect.fs + core/, section/, materials/, beam/)",
                                            "xSection tests studio: analytic EI / NA / GJ (check_xsection_tests.py)", "1.1-1.6, 2.1", "ROY_Test")}]}

SG = {"slug": "solve_gj", "title": "Solve GJ",
      "tagline": "Legacy: recompute the torsional stiffness GJ of an existing EI and Cross Section feature and write it back to its stored data and table.",
      "document": "xSection", "icon": "icons/final/solve_gj_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "GJ used to be a separate step. EI and Cross Section now computes GJ itself with the same solver, so Solve GJ changes nothing on a current model. It is kept so older documents still regenerate.",
           "useWhen": ["An older document still has it in the tree", "Not needed for new work"],
           "image": IMG + "fig04_roy_results.png", "caption": "GJ (orange) is already in every EI and Cross Section result."},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/solve_gj/shots/dialog.png",
           "params": [["Cross section feature", "One EI and Cross Section feature."]],
           "note": "GJ = 4 x sum(G x Iz) over the section's triangles, G = each body's Q66 (thin-plate Saint-Venant)."},
          {"type": "outputs", "keysTitle": "Outputs",
           "keys": [["(stored data)", "GJ of every station in the feature's CrossSectionAnalysis data and table."]],
           "messages": [["Error", "Select the cross section feature.", "Nothing selected."],
                        ["Error", "(missing data / station count mismatch)", "The selected feature has no stored sections."]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Fixed 2026-09-25", "body": "The recomputed GJ was written to a copy and lost; errors were swallowed. Both fixed."},
              {"kind": "limit", "head": "Redundant", "body": "Safe to delete from new models."}]},
          {"type": "reference", "rows": ref("GJ_Feature (+ section/gjAnalysis.fs, gjDataAccess.fs)",
                                            "SG1 in the xSection tests studio (stored GJ 125.31)", "1.5, 2.2", "xSection tests: SG1")}]}

ES = {"slug": "estimate_stiffness", "title": "Estimate Stiffness",
      "tagline": "The four flex numbers of any EI curve -- yours, a target, a competitor's -- between two contact points.",
      "document": "xSection", "icon": "docs/decks/_icons/estimate_stiffness_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "EI and Cross Section gives flex numbers for a modelled layup. Estimate Stiffness gives the same four numbers for any EI curve, so a measured or target curve can be compared on the same scale.",
           "useWhen": ["Rate a target or measured EI curve", "Compare two EI curves by the numbers", "Check a hand-edited EI profile"],
           "image": IMG + "fig05_flex_numbers.png", "caption": "The test behind the numbers: FCP-ACP simply supported, load at the mount."},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/estimate_stiffness/shots/dialog.png",
           "params": [["EI Edges", EI_EDGE],
                      ["FCP", "Front contact point (X only)."],
                      ["ACP", "Aft contact point (X only)."],
                      ["Stiffness estimates", "Read-only: prismatic lb/in and mm/30 kg; estimated (variable EI) lb/in and mm/30 kg."],
                      ["Recalculate", "Button: compute the numbers."]]},
          {"type": "tips", "items": [
              {"kind": "limit", "head": "Dialog only", "body": "Numbers are computed when you press Recalculate and do not follow later geometry changes."},
              {"kind": "limit", "head": "FCP before ACP", "body": "If FCP is not before ACP in X nothing is computed, silently."},
              {"kind": "tip", "head": "Short curves", "body": "An EI curve shorter than FCP-ACP is extended to reach them."}]},
          {"type": "reference", "rows": ref("estimateStiffness (+ beam/xSectBeamAnalysis.fs)", "none", "1.6, 2.3", "Test studio: Estimate Stiffness 1")}]}

ED = {"slug": "estimate_deflection", "title": "Estimate Deflection",
      "tagline": "Bend the ski under a load case: an EI curve, up to three supports and two applied loads, each spread over a width -- out comes the deflected shape.",
      "document": "xSection", "icon": "docs/decks/_icons/estimate_deflection_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Flex numbers are one load case. Estimate Deflection solves any: a bench test, a skier's weight fore and aft, a binding plate. Curvature = M / EI integrated twice gives the shape, zero at supports 1 and 2.",
           "useWhen": ["Predict a bench or on-snow deflection", "See the effect of a binding plate or mounting moment", "Find the EI that would give a shape (drag the curvature)"],
           "image": IMG + "fig08_deflection_case.png", "caption": "Test2: supports at +-700 mm, 60 N and 20 N loads -> 14.6 mm."},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/estimate_deflection/shots/dialog.png",
           "params": [["EI Edges", EI_EDGE],
                      ["Number of evaluation points", "20-500 (100); also EI samples per edge."],
                      ["Show shear/moment diagrams", "Draw V and M."],
                      ["Alter deformed beam curvature", "Drag curvature handles; outputs the matching EI (altered_EI)."],
                      ["Add plate/mounting conditions?", "Plate stiffness edge, reaction moment (N m, positive) and its x."],
                      ["Applied load data", "Load 3-600 N, balance between two loads; each: location, shape, width."],
                      ["Support load data", "Supports 1, 2 (optional 3 with its share); each: location, shape, width."],
                      ["Output Options", "Span (full EI / supports); Fit or Approximate."]]},
          {"type": "concept", "title": "Load shapes",
           "image": IMG + "fig09_load_shapes.png",
           "points": [{"head": "Spread over a width", "body": "Each shape integrates to the load's force."},
                      {"head": "Supports too", "body": "Reactions can be spread (Logistic suits a support pad)."},
                      {"head": "Known bug", "body": "Every distributed shape is computed as Logistic today (enum compared with strings). Point is correct."}]},
          {"type": "example", "title": "Example: Test2",
           "image": IMG + "fig08_deflection_case.png",
           "head": "EI eiTarget; supports x = -700 / 700; 80 N split 0.75: 60 N at -125, 20 N at 250 (100 mm wide)",
           "body": "The deflection_curve sags 14.6 mm near the middle. With 'Alter deformed beam curvature' on, the dragged shape gives altered_EI (dotted)."},
          {"type": "outputs", "keysTitle": "Outputs",
           "keys": [["deflection_curve", "The deflected shape, Z = deflection, true scale."],
                    ["altered_EI", "Optional: the EI curve that gives the dragged curvature (EI format)."]],
           "messages": [["Error", "fewer than 2 EI samples / all EI zero", ""],
                        ["Error", "supports 1 and 2 at the same x / zero span", ""]]},
          {"type": "tips", "items": [
              {"kind": "limit", "head": "Load shapes", "body": "Until fixed, Constant / Linear / Quadratic / Quintic all behave as Logistic."},
              {"kind": "limit", "head": "Support 3", "body": "Takes a fixed share of the load; the deflection is zero only at supports 1 and 2."},
              {"kind": "limit", "head": "Moment", "body": "The reaction moment cannot be negative."}]},
          {"type": "reference", "rows": ref("estimateDeflection (+ beam/estimateDeflectionSolver.fs)", "none", "2.4", "Test2 studio: Estimate Deflection 1")}]}

GB = {"slug": "generate_baseline", "title": "Generate baseline",
      "tagline": "Design the ski's unweighted side profile: a camber pocket between the rocker contact points and fore and aft rockers out to the tips -- optionally shaped by the ski's own EI.",
      "document": "xSection", "icon": "icons/final/generate_baseline_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "A baseline is a handful of targets -- camber height, rocker lengths, tip heights -- that must meet in one smooth curve. Generate baseline builds it from those numbers, levels it on its rocker low points, and can shape the camber as the ski actually bends.",
           "useWhen": ["Start a new ski's side profile", "Try camber / rocker targets quickly", "Shape the camber from the real EI"],
           "image": IMG + "fig06_baseline.png", "caption": "Test studio: NewTestBaseline, three edges (Z exaggerated 60 x)."},
          {"type": "concept", "title": "Camber and rocker",
           "image": IMG + "fig07_rocker_construction.png",
           "points": [{"head": "Camber pocket", "body": "Pinned at FRCP and ARCP. With EI: the bending shape under a load at the mount. Without: a cubic peaking at the mount."},
                      {"head": "Rocker", "body": "A quadratic leaving FRCP tangent to the camber, ending FCP height below that tangent (measured normal to it)."},
                      {"head": "Levelled", "body": "Rotated about the mount so both low points share Z; camber re-measured and corrected to 0.001 mm."}]},
          {"type": "dialogshot", "title": "The dialog", "screenshot": "docs/decks/generate_baseline/shots/dialog.png",
           "positions": {"Output type": [0.02, 0.056]},
           "params": [["Output type", "Curve per region (3 edges, one wire) or Single curve."],
                      ["Output curve name", "Default 'Baseline'."],
                      ["FCP", "Front contact point (X only)."],
                      ["ACP", "Aft contact point (X only)."],
                      ["Mount / load point", "Between FCP and ACP: where camber height is measured and the load acts."],
                      ["Baseline targets", "Camber height (0-15 mm), fore / aft rocker length, optional low-point distance, FCP / ACP height."],
                      ["Use EI profile", "+ EI edges: camber = the ski's real bending shape."],
                      ["Spline output", "Tolerance, max control points, degree."],
                      ["Add baseline sketch", "The measurement sketch (as Analyze baseline draws)."],
                      ["Create weighted baseline", "A second wire: camber flattened, rockers rotated with it."],
                      ["Debug", "Print setup, solver passes, analysis."]]},
          {"type": "example", "title": "Example: NewTestBaseline",
           "image": IMG + "fig06_baseline.png",
           "head": "Camber 5 mm, rockers 200 / 200, FCP height 10, ACP height 6, Use EI profile on",
           "body": "Camber exactly 5.0 mm at the mount (x = 0). The tips end 7.2 and 3.6 mm above the low points: tip height is measured from the camber tangent, not from Z = 0."},
          {"type": "outputs", "keysTitle": "Outputs",
           "keys": [["<Output curve name>", "The baseline wire (camber, fore rocker, aft rocker; or one spline)."],
                    ["Baseline (Weighted)", "Optional second wire."]],
           "messages": [["Info", "minimum-point distance clamped", "The requested rocker low point cannot be reached; the nearest reachable is used."],
                        ["Error", "mount not between FCP and ACP", ""]]},
          {"type": "tips", "items": [
              {"kind": "tip", "head": "Two camber heights", "body": "Generate baseline sets it at the mount; Analyze baseline reports the largest perpendicular distance -- they differ with an off-centre mount."},
              {"kind": "limit", "head": "No convergence notice", "body": "If 20 correction passes do not reach 0.001 mm, nothing is reported."}]},
          {"type": "reference", "rows": ref("generateBaseline (+ beam/generateBaselineSolver.fs, baselineCore.fs)", "none", "2.5", "Test studio: Generate baseline 1")}]}

AB = {"slug": "analyze_baseline", "title": "Analyze baseline",
      "tagline": "Measure an existing side profile -- camber height, rocker contact points and lengths, tip heights -- to compare a ski with its design targets.",
      "document": "xSection", "icon": "docs/decks/_icons/analyze_baseline_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Generate baseline builds a profile from targets; Analyze baseline goes the other way. Give it any baseline -- scanned, drawn, or generated -- and it reports the same quantities, and can draw them as a sketch.",
           "useWhen": ["Check a scanned or supplied ski against targets", "Verify a hand-drawn baseline", "Document a profile's numbers"],
           "image": IMG + "fig06_baseline.png", "caption": "The quantities it reports: minima, camber, FRCP / ARCP, rocker lengths, tip heights."},
          {"type": "dialog", "title": "The dialog",
           "params": [["Baseline edges", "The side profile (a tangent chain)."],
                      ["FCP / ACP", "Contact points (X only)."],
                      ["Calculated data", "Read-only: FB / AB minimum, max camber point, camber height, FRCP, FRCPL, FRCP tangent, FCPH, ARCP, ARCPL, ARCP tangent, ACPH."],
                      ["Output measurement sketch", "Chords, tangent lines and normals on the XZ plane."],
                      ["Recalculate", "Button (the values are also refreshed on every dialog change)."]]},
          {"type": "concept", "title": "How it measures",
           "image": IMG + "fig07_rocker_construction.png",
           "points": [{"head": "Camber", "body": "Largest perpendicular distance from the line between the two low points."},
                      {"head": "FRCP / ARCP", "body": "The lowest inflection in each half; FRCPL = its distance from FCP."},
                      {"head": "FCPH / ACPH", "body": "The tip's perpendicular distance to the tangent at FRCP / ARCP."}]},
          {"type": "tips", "items": [
              {"kind": "limit", "head": "Dialog only", "body": "Values are computed while editing and do not follow later geometry changes."},
              {"kind": "limit", "head": "No inflection", "body": "A half with no inflection leaves its fields empty."},
              {"kind": "limit", "head": "Name", "body": "The feature is spelled 'Analze baseline' in Onshape."}]},
          {"type": "reference", "rows": ref("analyzeBaseline (beam/analyzeBaseline.fs)", "none", "2.6", "Test2 studio: Analze baseline 1")}]}

UP = {"slug": "update_profile", "title": "Update profile",
      "tagline": "Inverse design: from an EI and Cross Section model and a target EI curve, propose the thickness profile that hits the target.",
      "document": "xSection", "icon": "docs/decks/_icons/update_profile_icon.svg", "status": STATUS,
      "slides": [
          {"type": "why", "title": "What it does",
           "problem": "Knowing the EI you want is easy; knowing the core thickness that gives it is not. Update profile uses the modelled sections to solve, station by station, for the thickness that meets a target EI curve.",
           "useWhen": ["Hit a target flex from an existing layup", "Scale a design part-way toward a target", "Estimate thickness changes quickly (DELTA / PERCENT)"],
           "image": IMG + "fig10_update_profile.png", "caption": "STD: section points above the neutral axis move up; output is a thickness curve."},
          {"type": "concept", "title": "Three solvers",
           "image": IMG + "fig10_update_profile.png",
           "points": [{"head": "STD", "body": "Full section model: move every point above the NA up by dt; bisection on dt until EI = target."},
                      {"head": "DELTA", "body": "Fit EI / width = alpha t^beta over all stations; solve t for the new EI."},
                      {"head": "PERCENT", "body": "Scale thickness by the EI ratio, using the fitted beta."}]},
          {"type": "dialogshot", "title": "The dialog (STD)", "screenshot": "docs/decks/update_profile/shots/dialog.png",
           "positions": {"Solver type": [0.02, 0.06], "Scale delta": [0.02, 0.473], "Recalculate": [0.02, 0.934]},
           "params": [["Solver type", "STD / DELTA / PERCENT."],
                      ["Output curve name", "Default 'Updated thickness'."],
                      ["Cross section feature", "The EI and Cross Section feature."],
                      ["Target EI profile", EI_EDGE],
                      ["Measured EI from", "Inherit (the model) or Query (edges)."],
                      ["Measured thickness from", "Inherit or Query (the Query edges are not used)."],
                      ["Scale delta", "Apply only part of the change: measured + factor x (target - measured)."],
                      ["FCP", "With ACP: read-only flex numbers of the target."],
                      ["ACP", "Aft contact point."],
                      ["Spline Output", "Fit / Approximate."],
                      ["Recalculate", "No effect today."]]},
          {"type": "outputs", "keysTitle": "Outputs",
           "keys": [["<Output curve name>", "Thickness wire, Z = thickness, true scale."],
                    ["profileUpdates (attribute)", "Per station: x, measured and updated thickness and EI; shown by the Profile Updates table (+ dt, dEI)."]],
           "messages": [["(none)", "A spline fit that fails draws red / magenta debug points; no error.", ""]]},
          {"type": "tips", "items": [
              {"kind": "limit", "head": "Growth above the NA", "body": "STD assumes added thickness goes on top (core / topsheet); a base-side change is not modelled."},
              {"kind": "limit", "head": "Coarse target read", "body": "The target EI is sampled 11 times per edge; stations outside it are skipped."},
              {"kind": "limit", "head": "Guard", "body": "A new thickness outside 0.1-200 mm is reset to the old one."}]},
          {"type": "reference", "rows": ref("updateProfile (+ tables/profileUpdatesTable.fs)", "none", "2.7", "Test studio: Update profile 1")}]}

for spec in (EI, SG, ES, ED, GB, AB, UP):
    json.dump(spec, open("docs/decks/%s/spec.json" % spec["slug"], "w"), indent=2)
    print("wrote", spec["slug"])
