"""Documentation tracker: which explainers / decks exist, and what the user has done with them.

Manifest: docs/status.json. Report: docs/STATUS.md (regenerated by every command).

Each doc records three hashes so changes are detected, not remembered:
    written_hash   the doc as Claude last wrote it     -> differs now = the USER edited it
    state_hash     the doc when its state was last set -> differs after approval = re-review needed
    sources_hash   the documented .fs files when the doc was written -> differs = code moved on

States: draft -> reviewed -> approved -> published. "published" = the user said to upload it to
Onshape; nothing goes to Onshape before that.

usage (from the repo root):
    python docs/doc_status.py                     rescan, rewrite STATUS.md
    python docs/doc_status.py wrote <id>          Claude (re)wrote the doc: refresh written/sources hashes
    python docs/doc_status.py set <id> <state> ["note"]   record a user decision
    python docs/doc_status.py show <id>
"""
import hashlib
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "status.json"
REPORT = ROOT / "docs" / "STATUS.md"
STATES = ["planned", "draft", "reviewed", "approved", "published"]


def load():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save(m):
    MANIFEST.write_text(json.dumps(m, indent=2) + "\n", encoding="utf-8")


def hash_files(paths):
    h = hashlib.sha256()
    found = False
    for p in sorted(paths):
        f = ROOT / p
        if f.exists():
            found = True
            h.update(p.encode())
            h.update(f.read_bytes())
    return h.hexdigest()[:12] if found else None


def doc_files(d):
    # The deck's reviewable content is the .pptx (the PDF is derived from it).
    return [d["path"]]


def flags(d):
    out = []
    cur = hash_files(doc_files(d))
    if cur is None:
        return ["missing"] if d["state"] != "planned" else []
    if d.get("written_hash") and cur != d["written_hash"]:
        out.append("edited by user")
    if d["state"] in ("approved", "published") and d.get("state_hash") and cur != d["state_hash"]:
        out.append("changed since " + d["state"])
    src = hash_files(d.get("sources", []))
    if d.get("sources_hash") and src != d["sources_hash"]:
        out.append("code changed since written")
    return out


def find(m, doc_id):
    for d in m["docs"]:
        if d["id"] == doc_id:
            return d
    sys.exit("no doc with id " + doc_id)


def report(m):
    lines = ["# Documentation status", "",
             "Generated by `python docs/doc_status.py` from `docs/status.json` -- do not edit by hand.", "",
             "States: planned -> draft -> reviewed -> approved -> published (uploaded to Onshape; only on the user's say-so).", ""]
    for kind, title in (("explainer", "Explainers (.md, repo only)"), ("deck", "Feature decks (.pptx -> .pdf for Onshape)")):
        lines += ["## " + title, "", "| id | title | state | flags | file | last change |", "|---|---|---|---|---|---|"]
        for d in m["docs"]:
            if d["kind"] != kind:
                continue
            last = d["history"][-1] if d.get("history") else {}
            f = ", ".join(flags(d)) or "-"
            lines.append("| {} | {} | **{}** | {} | `{}` | {} {} |".format(
                d["id"], d["title"], d["state"], f, d["path"], last.get("date", ""), last.get("note", "")))
        lines.append("")
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    m = load()
    today = date.today().isoformat()
    if len(argv) >= 2 and argv[0] == "wrote":
        d = find(m, argv[1])
        d["written_hash"] = hash_files(doc_files(d))
        d["sources_hash"] = hash_files(d.get("sources", []))
        if d["state"] == "planned":
            d["state"] = "draft"
        d.setdefault("history", []).append({"date": today, "state": d["state"], "note": "written by Claude"})
    elif len(argv) >= 3 and argv[0] == "set":
        d = find(m, argv[1])
        if argv[2] not in STATES:
            sys.exit("state must be one of " + ", ".join(STATES))
        d["state"] = argv[2]
        d["state_hash"] = hash_files(doc_files(d))
        d.setdefault("history", []).append({"date": today, "state": argv[2], "note": argv[3] if len(argv) > 3 else ""})
    elif len(argv) >= 2 and argv[0] == "show":
        d = find(m, argv[1])
        print(json.dumps(d, indent=2))
        print("flags:", flags(d))
        return
    save(m)
    report(m)
    print(REPORT.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main(sys.argv[1:])
