FeatureScript 2892;
import(path : "onshape/std/common.fs", version : "2892.0");

import(path : "1f26cb8c04ffde6fda7a1a15", version : "4d53db9298fc2e27f4024a61");


const tipTailBounds =
{
            (unitless) : [3, 23, 50]
        } as IntegerBoundSpec;

const rslBounds =
{
            (unitless) : [10, 80, 200]
        } as IntegerBoundSpec;

const sigFigBounds =
{
            (unitless) : [3, 4, 10]
        } as IntegerBoundSpec;

export enum exportUnits
{
    MILLIMETER,
    INCH,
    CENTIMETER
}

export enum edgeQueryType
{
    FACE,
    EDGES
}


export function editingLogic(context is Context, id is Id, oldDefinition is map, definition is map, isCreating is boolean, specifiedParameters is map) returns map
{
    var updatedDef = definition;
    if (definition.sourceType == edgeQueryType.FACE)
    {
        updatedDef.fptEdges = qUnion([qAdjacent(updatedDef.footprintFace, AdjacencyType.EDGE, EntityType.EDGE)]);
    }

    if (!isQueryEmpty(context, updatedDef.fptEdges) && !isQueryEmpty(context, updatedDef.rslQuery))
    {
        try
        {
            var fptPath = constructPath(context, qUnion([updatedDef.fptEdges]));
            var analysisMap = analyzeFootprint(context, id + 'getFootprintDataEL', fptPath, definition.rslQuery, false);

            var analysisMapKeys = keys(analysisMap);

            var sharedKeys = filter(analysisMapKeys, function(x)
            {
                return isIn(x, keys(updatedDef));
            });
            for (var sharedKey in sharedKeys)
            {
                updatedDef[(sharedKey)] = analysisMap[(sharedKey)];
            }
        }
        catch
        {
        }
    }

    return updatedDef;
}


annotation { "Feature Type Name" : "Generate Footprint Points", "Editing Logic Function" : "editingLogic" }
export const getFootprintPoints = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {
        annotation { "Name" : "Geometry Selection Type", 'Default' : edgeQueryType.FACE, "UIHint" : UIHint.HORIZONTAL_ENUM }
        definition.sourceType is edgeQueryType;

        if (definition.sourceType == edgeQueryType.FACE)
        {
            annotation { "Name" : "Footprint face", "Filter" : EntityType.FACE, "MaxNumberOfPicks" : 1 }
            definition.footprintFace is Query;
        }

        else if (definition.sourceType == edgeQueryType.EDGES)
        {
            annotation { "Name" : "Footprint Edges", "Filter" : EntityType.EDGE || BodyType.WIRE }
            definition.fptEdges is Query;
        }

        annotation { "Name" : "RSL Line", "Filter" : EntityType.EDGE && GeometryType.LINE, "MaxNumberOfPicks" : 1 }
        definition.rslQuery is Query;

        annotation { "Name" : "Include Points", "Filter" : EntityType.VERTEX }
        definition.includePoints is Query;

        annotation { "Name" : "hasFootprintAnalysis", "Default" : false, "UIHint" : UIHint.ALWAYS_HIDDEN }
        definition.hasFootprintData is boolean;

        annotation { "Group Name" : "Footprint data", "Collapsed By Default" : true } // data about footprint
        {
            annotation { "Name" : "Average radius", "Description" : 'Average radius between inflection points. Value is generated by evaluating instantaneious radious of curvature at 200 equally spaced points between inflection points and averaging those radaii', "UIHint" : UIHint.READ_ONLY }
            definition.avgRadiusSTR is string;

            annotation { "Name" : "Dimensions", "UIHint" : UIHint.READ_ONLY,
                        "Description" : 'Widest FB - Waist - Widest AB'
                    }
            definition.dimSTR is string;


            annotation { "Group Name" : "Natural radaii", "Collapsed By Default" : true }
            {
                annotation { "Name" : "Natural radius - WIDEST", "UIHint" : UIHint.READ_ONLY,
                            "Description" : "Natural radius between widest points. Value is obtained by creating an arc that is concident with the widest forebody and aftbody points and the waist of the ski. Note that the waist of this 'natural radius' will almost NEVER coincide with the footprint waist (y value and location)." }
                definition.natRadWideSTR is string;

                annotation { "Name" : "Natural radius - INFLECTION", "UIHint" : UIHint.READ_ONLY,
                            "Description" : "Natural radius between widest points. Value is obtained by creating an arc that is concident with the widest forebody and aftbody points and the waist of the ski. Note that the waist of this 'natural radius' will almost NEVER coincide with the footprint waist (y value and location)." }
                definition.natRadInflectSTR is string;
            }

            annotation { "Group Name" : "Taper angles", "Collapsed By Default" : true }
            {
                annotation { "Name" : "Taper Angle - WIDEST", "UIHint" : UIHint.READ_ONLY, "Description" : 'Taper angle between ski center and line connecting widest points' }
                isAngle(definition.taWIDEST, ANGLE_360_BOUNDS);

                annotation { "Name" : "Taper Angle - INFLECTION", "UIHint" : UIHint.READ_ONLY, "Description" : 'Taper angle between ski center and line connecting inflection points' }
                isAngle(definition.taINFLECTION, ANGLE_360_BOUNDS);

                annotation { "Group Name" : "Footprint angles at contacts", "Collapsed By Default" : true }
                {
                    annotation { "Name" : "Footprint angle @ FCP", "Description" : 'Footprint angle at FCP. Positive is tapered, negative is untapered', "UIHint" : UIHint.READ_ONLY }
                    isAngle(definition.fcpAngle, ANGLE_360_BOUNDS);

                    annotation { "Name" : "Footprint angle @ ACP", "Description" : 'Footprint angle at ACP. Positive is untapered, negative is tapered', "UIHint" : UIHint.READ_ONLY }
                    isAngle(definition.acpAngle, ANGLE_360_BOUNDS);
                }
            }

            annotation { "Group Name" : "Widest/Inflection points", "Collapsed By Default" : true }
            {
                annotation { "Name" : "FB Widest from FCP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between FCP and FB widest point. Positive indicates widest point towards mount point" }
                isLength(definition.widestFBfromFCP, LENGTH_BOUNDS);

                annotation { "Name" : "FB Inflection from FCP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between FCP and FB inflection point. Positive indicates widest point towards mount point" }
                isLength(definition.inflectionFBfromFCP, LENGTH_BOUNDS);

                annotation { "Name" : "FB inflection to widest", "UIHint" : UIHint.READ_ONLY }
                isLength(definition.fbInflectionToWidest, LENGTH_BOUNDS);

                annotation { "Name" : "AB Widest from ACP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between ACP and AB widest point. Negative indicates widest point towards mount point" }
                isLength(definition.widestABfromACP, LENGTH_BOUNDS);

                annotation { "Name" : "AB Inflection from ACP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between ACP and AB inflection point. Negative indicates widest point towards mount point" }
                isLength(definition.inflectionABfromACP, LENGTH_BOUNDS);

                annotation { "Name" : "AB inflection to widest", "UIHint" : UIHint.READ_ONLY }
                isLength(definition.abInflectionToWidest, LENGTH_BOUNDS);
            }

        }

        annotation { "Group Name" : "Table Formatting", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Table units", "Default" : exportUnits.MILLIMETER }
            definition.tableUnits is exportUnits;

            annotation { "Name" : "Table sig figs" }
            isInteger(definition.sigFigs, sigFigBounds);

            annotation { "Name" : "Remove units from table?", "Default" : false }
            definition.cleanUnits is boolean;

            annotation { "Name" : "Number of Tip Points" }
            isInteger(definition.tipCount, tipTailBounds);

            annotation { "Name" : "Flip Tip Points?", "Default" : false }
            definition.flipTip is boolean;

            annotation { "Name" : "Number of RSL Points" }
            isInteger(definition.rslCount, rslBounds);

            annotation { "Name" : "Flip RSL Points?", "Default" : false }
            definition.flipRSL is boolean;

            annotation { "Name" : "Number of Tail Points" }
            isInteger(definition.tailCount, tipTailBounds);

            annotation { "Name" : "Flip Tail Points?", "Default" : false }
            definition.flipTail is boolean;
        }

        annotation { "Group Name" : "Additional options", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Retain Curves in Part Studio?" }
            definition.retainCurves is boolean;

            annotation { "Name" : "Retain FCP/ACP Planes in Part Studio?" }
            definition.retainPlanes is boolean;

            annotation { "Name" : "Create Sketch From Points" }
            definition.sketchPoints is boolean;
        }
        
        annotation { "Name" : "Show curvature combs?", "Default" : true }
        definition.showCurvature is boolean;
        

    }
    {
        //0. Was a face selected? If so, set definition.fptEdges to edges of that face.

        if (definition.sourceType == edgeQueryType.FACE)
        {
            definition.fptEdges = qUnion([qAdjacent(definition.footprintFace, AdjacencyType.EDGE, EntityType.EDGE)]);
        }

        //1. Combine all of the edges into one composite curve

        definition.fptEdges = dissolveWires(definition.fptEdges);

        opExtractWires(context, id + "fptWires", {
                    "edges" : definition.fptEdges
                });

        // test to see if wires go beyond front plane. If they do, split with front plane

        var wireBox = evBox3d(context, {
                "topology" : qUnion([qCreatedBy(id + "fptWires", EntityType.BODY)]),
                "tight" : true
            });

        if (wireBox.minCorner[1] < 0 * millimeter)
        {
            opSplitPart(context, id + "splitWireOverflow", {
                        "targets" : qUnion([qCreatedBy(id + "fptWires", EntityType.BODY)]),
                        "tool" : plane(vector(0, 0, 0) * millimeter, vector(0, 1, 0)),
                        "keepType" : SplitOperationKeepType.KEEP_FRONT
                    });
        }

        definition.fptEdges = qCreatedBy(id + "fptWires", EntityType.EDGE);

        //2. Create ACP, FCP Planes at the end of definition.rslQuery to split the composite curve

        // get fcp and acp points
        var cpLine1 = evEdgeTangentLine(context, {
                "edge" : definition.rslQuery,
                "parameter" : 0
            });

        var cpLine2 = evEdgeTangentLine(context, {
                "edge" : definition.rslQuery,
                "parameter" : 1
            });

        //println('cpLine1 = '~cpLine1);
        //println('cpLine2 = '~cpLine2);

        var fcpORGIN = cpLine1.origin;
        var acpORIGIN = cpLine2.origin;
        var mrsORIGIN = evEdgeTangentLine(context, {
                    "edge" : definition.rslQuery,
                    "parameter" : 0.5
                }).origin;

        if (cpLine1.origin[0] > cpLine2.origin[0])
        // if the extents of the line are switched from expectations, switch definitions so that varaibles match expectations
        //FCPx < ACPx
        {
            fcpORGIN = cpLine2.origin;
            acpORIGIN = cpLine1.origin;
        }

        opPlane(context, id + "fcpPlane", {
                    "plane" : plane(fcpORGIN, vector(1, 0, 0))
                });

        var fcpPlane = qCreatedBy(id + "fcpPlane", EntityType.FACE);

        opPlane(context, id + "acpPlane", {
                    "plane" : plane(acpORIGIN, vector(1, 0, 0))
                });

        var acpPlane = qCreatedBy(id + "acpPlane", EntityType.FACE);

        // Only attempt a split if at least one wire body strictly straddles the
        // plane (minX < planeX < maxX per body).  The combined wireBox can span
        // the plane even when every individual body only touches it at a vertex,
        // which causes SPLIT_FAILED.  Checking per-body avoids the attempt —
        // and the resulting logged warning — entirely.
        var wireBodies = evaluateQuery(context, qCreatedBy(id + "fptWires", EntityType.BODY));

        var fcpSplitDone = false;
        var anyBodyCrossesFcp = false;
        for (var body in wireBodies)
        {
            var bodyBox = evBox3d(context, { "topology" : body, "tight" : true });
            if (bodyBox.minCorner[0] < fcpORGIN[0] && fcpORGIN[0] < bodyBox.maxCorner[0])
            {
                anyBodyCrossesFcp = true;
                break;
            }
        }
        if (anyBodyCrossesFcp)
        {
            opSplitPart(context, id + "fcpSplit", {
                        "targets" : qCreatedBy(id + "fptWires", EntityType.BODY),
                        "tool" : fcpPlane
                    });
            fcpSplitDone = true;
        }

        var acpTarget = fcpSplitDone
            ? qSplitBy(id + "fcpSplit", EntityType.BODY, false)
            : qCreatedBy(id + "fptWires", EntityType.BODY);

        var acpSplitDone = false;
        var anyBodyCrossesAcp = false;
        var acpBodies = evaluateQuery(context, acpTarget);
        for (var body in acpBodies)
        {
            var bodyBox = evBox3d(context, { "topology" : body, "tight" : true });
            if (bodyBox.minCorner[0] < acpORIGIN[0] && acpORIGIN[0] < bodyBox.maxCorner[0])
            {
                anyBodyCrossesAcp = true;
                break;
            }
        }
        if (anyBodyCrossesAcp)
        {
            opSplitPart(context, id + "acpSplit", {
                        "targets" : acpTarget,
                        "tool" : acpPlane
                    });
            acpSplitDone = true;
        }

        var rslEdge = acpSplitDone
            ? qSplitBy(id + "acpSplit", EntityType.BODY, true)
            : acpTarget;

        setProperty(context, {
                    "entities" : rslEdge,
                    "propertyType" : PropertyType.NAME,
                    "value" : "RSL Curve"
                });

        var tipPoints = [];
        if (fcpSplitDone)
        {
            var tipEdge = qSplitBy(id + "fcpSplit", EntityType.BODY, true);
            setProperty(context, {
                        "entities" : tipEdge,
                        "propertyType" : PropertyType.NAME,
                        "value" : "Tip Curve"
                    });
            tipPoints = genPointArray(context, id, tipEdge, 'TIP', definition.tipCount, definition.includePoints, fcpORGIN, false, definition.sketchPoints, 'Tip_Sketch');
            if (definition.flipTip)
            {
                tipPoints = reverse(tipPoints);
            }
        }

        var rslPoints = genPointArray(context, id, rslEdge, 'RSL', definition.rslCount, definition.includePoints, mrsORIGIN, false, definition.sketchPoints, 'RSL_Sketch');
        if (definition.flipRSL)
        {
            rslPoints = reverse(rslPoints);
        }

        var tailPoints = [];
        if (acpSplitDone)
        {
            var tailEdge = qSplitBy(id + "acpSplit", EntityType.BODY, false);
            setProperty(context, {
                        "entities" : tailEdge,
                        "propertyType" : PropertyType.NAME,
                        "value" : "Tail Curve"
                    });
            tailPoints = genPointArray(context, id, tailEdge, 'TAIL', definition.tailCount, definition.includePoints, acpORIGIN, false, definition.sketchPoints, 'Tail_Sketch');
            if (definition.flipTail)
            {
                tailPoints = reverse(tailPoints);
            }
        }

        // add point arrays as attributes to the origin so we can access the data in a query for the table.

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tipEdgePoints",
                    "attribute" : tipPoints
                });

        //Set Point Colors
        for (var tpPt in tipPoints)
        {
            addDebugPoint(context, tpPt + fcpORGIN, DebugColor.RED);
        }

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "rslEdgePoints",
                    "attribute" : rslPoints
                });

        for (var tpPt in rslPoints)
        {
            addDebugPoint(context, tpPt + mrsORIGIN, DebugColor.BLUE);
        }

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tailEdgePoints",
                    "attribute" : tailPoints
                });

        for (var tpPt in tailPoints)
        {
            addDebugPoint(context, tpPt + acpORIGIN, DebugColor.GREEN);
        }

        if (!definition.retainPlanes)
        {
            opDeleteBodies(context, id + "deleteFCPPlane", {
                        "entities" : qCreatedBy(id + "fcpPlane", EntityType.BODY)
                    });

            opDeleteBodies(context, id + "deleteACPPlane", {
                        "entities" : qCreatedBy(id + "acpPlane", EntityType.BODY)
                    });
        }

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tableFormat",
                    "attribute" : { 'tableUnits' : definition.tableUnits, 'cleanUnits' : definition.cleanUnits, 'sigFigs' : definition.sigFigs }
                });


        try
        {
            var fptPath = constructPath(context, qUnion([definition.fptEdges]));
            analyzeFootprint(context, id + 'getFootprintDataBody', fptPath, definition.rslQuery, definition.showCurvature);
            /*
               println('ANALYSIS MAP: ' );
               //println(analysisMap);
               for (var key in keys(analysisMap))
               {
               println(key ~ ': ' ~ toString(analysisMap[(key)]));
               }
             */
        }
        catch
        {
            reportFeatureInfo(context, id, 'FOOTPRINT MUST BE CONTINUIOUS. NO FOOTPRINT DATA ANALYSIS. Cannot form a tangent path from selected edges');
        }

        if (!definition.retainCurves)
        {
            opDeleteBodies(context, id + "deleteCurves", {
                        "entities" : qCreatedBy(id + "fptWires", EntityType.BODY)
                    });
        }

    });

function genPointArray(context is Context, id is Id, targetCurve is Query, curveName is string, numPoints is number, includePoints is Query, refOrigin is Vector, reverseOrder is boolean, createSketch is boolean, sketchID is string)
{

    var lengthParams = range(0, 1, numPoints); // length increments along path to get points at.


    var edges = evaluateQuery(context, qOwnedByBody(targetCurve, EntityType.EDGE));

    addDebugEntities(context, qUnion(edges), DebugColor.CYAN);


    var edgePath = constructPath(context, qUnion(edges));


    var pathLines is array = evPathTangentLines(context, edgePath, lengthParams).tangentLines;
    var expPoints is array = [];
    for (var i = 0; i < size(pathLines); i += 1)
    {
        expPoints = append(expPoints, pathLines[i].origin - refOrigin);
    }

    //expPoints = sort(expPoints, function(a, b) {return (a[0] - b[0]);});
    if (reverseOrder)
    {
        expPoints = reverse(expPoints);
    }
    /*
       //println(curveName~' Points are:');
       for (var i = 0; i < size(expPoints); i += 1)
       {
       //println(expPoints[i][0].value*1000~', '~expPoints[i][1].value*1000);
       }
     */

    if (createSketch)
    {
        var fptSketch = newSketchOnPlane(context, id + ("sketch" ~ sketchID), {
                "sketchPlane" : plane(refOrigin, vector(0, 0, 1))
            });
        for (var i = 0; i < size(expPoints); i += 1)
        {
            skPoint(fptSketch, ("point" ~ i ~ sketchID), {
                        "position" : vector(expPoints[i][0], expPoints[i][1])
                    });
        }

        skSolve(fptSketch);

        /*
           setProperty(context, {
           "entities" : qOwnedByBody(fptSketch),
           "propertyType" : PropertyType.NAME,
           "value" : sketchID
           });
         */

    }

    return expPoints;
}


annotation { "Table Type Name" : "Footprint Points" }
export const fptPointTable = defineTable(function(context is Context, definition is map) returns TableArray
    precondition
    {
        // Define the parameters of the table type
    }
    {
        var columnDefinitions = [ //tableColumnDefinition("region", "Region"),
            tableColumnDefinition("x", "X - Value"),
            tableColumnDefinition("y", "Y - Value")
            //,tableColumnDefinition("z", "Z - Value")
        ];

        var tipRows = [];
        var rslRows = [];
        var tailRows = [];

        //1. Tip Points

        const tipPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "tipEdgePoints"
                });

        var tableFormat = getAttributes(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tableFormat"
                })[0];

        //println(tableFormat);

        var scaleFactor = 1;
        var suffixStr = '';
        if (tableFormat.tableUnits == exportUnits.MILLIMETER)
        {
            scaleFactor = 1000;
            suffixStr = ' mm';
        }

        if (tableFormat.tableUnits == exportUnits.INCH)
        {
            scaleFactor = 1000 / 25.4;
            suffixStr = ' in';
        }
        if (tableFormat.tableUnits == exportUnits.CENTIMETER)
        {
            scaleFactor = 100;
            suffixStr = ' cm';
        }

        //println('TABLE SCALEFACTOR = ' ~ scaleFactor);
        //println('TABLE SUFFIX STR = ' ~ suffixStr);


        for (var pt in tipPoints)
        {
            tipRows = append(tipRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));

        }

        //2. RSL Points
        const rslPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "rslEdgePoints"
                });

        for (var pt in rslPoints)
        {
            rslRows = append(rslRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));
        }
        //3. Tail Points
        const tailPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "tailEdgePoints"
                });

        for (var pt in tailPoints)
        {
            tailRows = append(tailRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));
        }


        // Compute the table



        return tableArray([table("TIP Points", columnDefinitions, tipRows), table("RSL Points", columnDefinitions, rslRows), table("TAIL points", columnDefinitions, tailRows)]);
    });

export function splitStr(splitStr is string, splitChar is string) returns array
{
    var retArray = [];
    var regexp = ".*" ~ splitChar ~ ".*";
    var stringArray = splitIntoCharacters(splitStr);
    var iterString is string = '';

    for (var i = 0; i < size(stringArray); i += 1)
    {
        if (!match(stringArray[i], regexp).hasMatch)
        {
            iterString = iterString ~ stringArray[i];

            if (i == size(stringArray) - 1)
            {
                retArray = append(retArray, iterString);
            }
        }
        else
        {
            retArray = append(retArray, iterString);
            iterString = '';
        }

    }

    return retArray;
}

export function formatTableValue(context is Context, val is ValueWithUnits, scaleFactor is number, sigFigs is number, suffixStr is string, cleanUnits is boolean)
{
    if (cleanUnits)
    {
        return roundToPrecision(val.value * scaleFactor, sigFigs);
    }
    else if (!cleanUnits)
    {
        return roundToPrecision(val.value * scaleFactor, sigFigs) ~ suffixStr;
    }
}