FeatureScript 2892;
import(path : "onshape/std/common.fs", version : "2892.0");

import(path : "1f26cb8c04ffde6fda7a1a15", version : "4d53db9298fc2e27f4024a61");


const tipTailBounds =
{
            (unitless) : [3, 23, 50]
        } as IntegerBoundSpec;

const rslBounds =
{
            (unitless) : [10, 80, 200]
        } as IntegerBoundSpec;

const sigFigBounds =
{
            (unitless) : [3, 4, 10]
        } as IntegerBoundSpec;

export enum exportUnits
{
    MILLIMETER,
    INCH,
    CENTIMETER
}

export enum edgeQueryType
{
    FACE,
    EDGES
}


export function editingLogic(context is Context, id is Id, oldDefinition is map, definition is map, isCreating is boolean, specifiedParameters is map) returns map
{
    var updatedDef = definition;
    if (definition.sourceType == edgeQueryType.FACE)
    {
        updatedDef.fptEdges = qUnion([qAdjacent(updatedDef.footprintFace, AdjacencyType.EDGE, EntityType.EDGE)]);
    }

    if (!isQueryEmpty(context, updatedDef.fptEdges) && !isQueryEmpty(context, updatedDef.rslQuery))
    {
        try
        {
            var fptPath = constructPath(context, qUnion([updatedDef.fptEdges]));
            var analysisMap = analyzeFootprint(context, id + 'getFootprintDataEL', fptPath, definition.rslQuery, false);

            var analysisMapKeys = keys(analysisMap);

            var sharedKeys = filter(analysisMapKeys, function(x)
            {
                return isIn(x, keys(updatedDef));
            });
            for (var sharedKey in sharedKeys)
            {
                updatedDef[(sharedKey)] = analysisMap[(sharedKey)];
            }
        }
        catch
        {
        }
    }

    return updatedDef;
}


annotation { "Feature Type Name" : "Generate Footprint Points", "Editing Logic Function" : "editingLogic" }
export const getFootprintPoints = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {
        annotation { "Name" : "Geometry Selection Type", 'Default' : edgeQueryType.FACE, "UIHint" : UIHint.HORIZONTAL_ENUM }
        definition.sourceType is edgeQueryType;

        if (definition.sourceType == edgeQueryType.FACE)
        {
            annotation { "Name" : "Footprint face", "Filter" : EntityType.FACE, "MaxNumberOfPicks" : 1 }
            definition.footprintFace is Query;
        }

        else if (definition.sourceType == edgeQueryType.EDGES)
        {
            annotation { "Name" : "Footprint Edges", "Filter" : EntityType.EDGE || BodyType.WIRE }
            definition.fptEdges is Query;
        }

        annotation { "Name" : "RSL Line", "Filter" : EntityType.EDGE && GeometryType.LINE, "MaxNumberOfPicks" : 1 }
        definition.rslQuery is Query;

        annotation { "Name" : "Include Points", "Filter" : EntityType.VERTEX }
        definition.includePoints is Query;

        annotation { "Name" : "hasFootprintAnalysis", "Default" : false, "UIHint" : UIHint.ALWAYS_HIDDEN }
        definition.hasFootprintData is boolean;

        annotation { "Group Name" : "Footprint data", "Collapsed By Default" : true } // data about footprint
        {
            annotation { "Name" : "Average radius", "Description" : 'Average radius between inflection points. Value is generated by evaluating instantaneious radious of curvature at 200 equally spaced points between inflection points and averaging those radaii', "UIHint" : UIHint.READ_ONLY }
            definition.avgRadiusSTR is string;

            annotation { "Name" : "Dimensions", "UIHint" : UIHint.READ_ONLY,
                        "Description" : 'Widest FB - Waist - Widest AB'
                    }
            definition.dimSTR is string;


            annotation { "Group Name" : "Natural radaii", "Collapsed By Default" : true }
            {
                annotation { "Name" : "Natural radius - WIDEST", "UIHint" : UIHint.READ_ONLY,
                            "Description" : "Natural radius between widest points. Value is obtained by creating an arc that is concident with the widest forebody and aftbody points and the waist of the ski. Note that the waist of this 'natural radius' will almost NEVER coincide with the footprint waist (y value and location)." }
                definition.natRadWideSTR is string;

                annotation { "Name" : "Natural radius - INFLECTION", "UIHint" : UIHint.READ_ONLY,
                            "Description" : "Natural radius between widest points. Value is obtained by creating an arc that is concident with the widest forebody and aftbody points and the waist of the ski. Note that the waist of this 'natural radius' will almost NEVER coincide with the footprint waist (y value and location)." }
                definition.natRadInflectSTR is string;
            }

            annotation { "Group Name" : "Taper angles", "Collapsed By Default" : true }
            {
                annotation { "Name" : "Taper Angle - WIDEST", "UIHint" : UIHint.READ_ONLY, "Description" : 'Taper angle between ski center and line connecting widest points' }
                isAngle(definition.taWIDEST, ANGLE_360_BOUNDS);

                annotation { "Name" : "Taper Angle - INFLECTION", "UIHint" : UIHint.READ_ONLY, "Description" : 'Taper angle between ski center and line connecting inflection points' }
                isAngle(definition.taINFLECTION, ANGLE_360_BOUNDS);

                annotation { "Group Name" : "Footprint angles at contacts", "Collapsed By Default" : true }
                {
                    annotation { "Name" : "Footprint angle @ FCP", "Description" : 'Footprint angle at FCP. Positive is tapered, negative is untapered', "UIHint" : UIHint.READ_ONLY }
                    isAngle(definition.fcpAngle, ANGLE_360_BOUNDS);

                    annotation { "Name" : "Footprint angle @ ACP", "Description" : 'Footprint angle at ACP. Positive is untapered, negative is tapered', "UIHint" : UIHint.READ_ONLY }
                    isAngle(definition.acpAngle, ANGLE_360_BOUNDS);
                }
            }

            annotation { "Group Name" : "Widest/Inflection points", "Collapsed By Default" : true }
            {
                annotation { "Name" : "FB Widest from FCP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between FCP and FB widest point. Positive indicates widest point towards mount point" }
                isLength(definition.widestFBfromFCP, LENGTH_BOUNDS);

                annotation { "Name" : "FB Inflection from FCP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between FCP and FB inflection point. Positive indicates widest point towards mount point" }
                isLength(definition.inflectionFBfromFCP, LENGTH_BOUNDS);

                annotation { "Name" : "FB inflection to widest", "UIHint" : UIHint.READ_ONLY }
                isLength(definition.fbInflectionToWidest, LENGTH_BOUNDS);

                annotation { "Name" : "AB Widest from ACP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between ACP and AB widest point. Negative indicates widest point towards mount point" }
                isLength(definition.widestABfromACP, LENGTH_BOUNDS);

                annotation { "Name" : "AB Inflection from ACP", "UIHint" : UIHint.READ_ONLY, "Description" : "Distance between ACP and AB inflection point. Negative indicates widest point towards mount point" }
                isLength(definition.inflectionABfromACP, LENGTH_BOUNDS);

                annotation { "Name" : "AB inflection to widest", "UIHint" : UIHint.READ_ONLY }
                isLength(definition.abInflectionToWidest, LENGTH_BOUNDS);
            }

        }

        annotation { "Group Name" : "Table Formatting", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Table units", "Default" : exportUnits.MILLIMETER }
            definition.tableUnits is exportUnits;

            annotation { "Name" : "Table sig figs" }
            isInteger(definition.sigFigs, sigFigBounds);

            annotation { "Name" : "Remove units from table?", "Default" : false }
            definition.cleanUnits is boolean;

            annotation { "Name" : "Number of Tip Points" }
            isInteger(definition.tipCount, tipTailBounds);

            annotation { "Name" : "Flip Tip Points?", "Default" : false }
            definition.flipTip is boolean;

            annotation { "Name" : "Number of RSL Points" }
            isInteger(definition.rslCount, rslBounds);

            annotation { "Name" : "Flip RSL Points?", "Default" : false }
            definition.flipRSL is boolean;

            annotation { "Name" : "Number of Tail Points" }
            isInteger(definition.tailCount, tipTailBounds);

            annotation { "Name" : "Flip Tail Points?", "Default" : false }
            definition.flipTail is boolean;
        }

        annotation { "Group Name" : "Additional options", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Retain Curves in Part Studio?" }
            definition.retainCurves is boolean;

            annotation { "Name" : "Retain FCP/ACP Planes in Part Studio?" }
            definition.retainPlanes is boolean;

            annotation { "Name" : "Create Sketch From Points" }
            definition.sketchPoints is boolean;
        }
        
        annotation { "Name" : "Show curvature combs?", "Default" : true }
        definition.showCurvature is boolean;
        

    }
    {
        //0. Was a face selected? If so, set definition.fptEdges to edges of that face.

        if (definition.sourceType == edgeQueryType.FACE)
        {
            definition.fptEdges = qUnion([qAdjacent(definition.footprintFace, AdjacencyType.EDGE, EntityType.EDGE)]);
        }

        //1. Resolve source edges
        definition.fptEdges = dissolveWires(definition.fptEdges);

        //2. Evaluate FCP/ACP positions BEFORE wire extraction so we can use them
        //   to categorize individual edges (avoids opSplitPart on closed loops).
        var cpLine1 = evEdgeTangentLine(context, {
                "edge" : definition.rslQuery,
                "parameter" : 0
            });

        var cpLine2 = evEdgeTangentLine(context, {
                "edge" : definition.rslQuery,
                "parameter" : 1
            });

        var fcpORGIN = cpLine1.origin;
        var acpORIGIN = cpLine2.origin;
        var mrsORIGIN = evEdgeTangentLine(context, {
                    "edge" : definition.rslQuery,
                    "parameter" : 0.5
                }).origin;

        if (cpLine1.origin[0] > cpLine2.origin[0])
        // FCPx < ACPx
        {
            fcpORGIN = cpLine2.origin;
            acpORIGIN = cpLine1.origin;
        }

        var fcpX = fcpORGIN[0];
        var acpX = acpORIGIN[0];

        //3. Create FCP and ACP planes now — needed as split tools for spanning edges
        //   before wire extraction happens.
        opPlane(context, id + "fcpPlane", {
                    "plane" : plane(fcpORGIN, vector(1, 0, 0))
                });

        opPlane(context, id + "acpPlane", {
                    "plane" : plane(acpORIGIN, vector(1, 0, 0))
                });

        //4. Categorize individual edges into tip / RSL / tail.
        //   - Y=0 centerline closing edges are skipped (they form a closed loop).
        //   - Edges that span a contact plane are extracted into a single-edge wire
        //     and split at that plane; opSplitPart succeeds because each temp wire
        //     is an open path (not a closed loop).
        const spanTol = 1e-6 * meter;

        var allEdges = evaluateQuery(context, definition.fptEdges);
        var tipEdgesArr = [];   // non-spanning edges routed to tip zone
        var rslEdgesArr = [];
        var tailEdgesArr = [];
        var tipSpanBodies = [];   // wire-body Queries from spanning-edge splits
        var rslSpanBodies = [];
        var tailSpanBodies = [];
        var spanIdx = 0;

        for (var edge in allEdges)
        {
            var edgeBox = evBox3d(context, { "topology" : edge, "tight" : true });

            // Skip Y=0 centerline closing edges
            if (edgeBox.maxCorner[1] < spanTol)
                continue;

            var crossesFcp = edgeBox.minCorner[0] + spanTol < fcpX && fcpX < edgeBox.maxCorner[0] - spanTol;
            var crossesAcp = edgeBox.minCorner[0] + spanTol < acpX && acpX < edgeBox.maxCorner[0] - spanTol;

            if (!crossesFcp && !crossesAcp)
            {
                // Non-spanning: route by bounding-box midpoint
                var edgeMidX = (edgeBox.minCorner[0] + edgeBox.maxCorner[0]) / 2;
                if (edgeMidX < fcpX)
                    tipEdgesArr = append(tipEdgesArr, edge);
                else if (edgeMidX > acpX)
                    tailEdgesArr = append(tailEdgesArr, edge);
                else
                    rslEdgesArr = append(rslEdgesArr, edge);
            }
            else
            {
                // Spanning edge: extract into a temp single-edge wire, then split.
                var tempId = id + ("spanWire" ~ spanIdx);
                spanIdx += 1;
                opExtractWires(context, tempId, { "edges" : edge });

                if (crossesFcp)
                {
                    opSplitPart(context, tempId + "F", {
                                "targets" : qCreatedBy(tempId, EntityType.BODY),
                                "tool" : qCreatedBy(id + "fcpPlane", EntityType.FACE)
                            });

                    // Identify tip piece (maxX ≈ fcpX) vs RSL/tail piece (minX ≈ fcpX)
                    // by evaluating the bounding box of one side.
                    var fcpSideTrue = qSplitBy(tempId + "F", EntityType.BODY, true);
                    var fcpSideTrueBox = evBox3d(context, { "topology" : fcpSideTrue, "tight" : true });
                    var tipPieceQ = fcpSideTrueBox.maxCorner[0] < fcpX + spanTol
                        ? fcpSideTrue
                        : qSplitBy(tempId + "F", EntityType.BODY, false);
                    var rslTailPieceQ = fcpSideTrueBox.maxCorner[0] < fcpX + spanTol
                        ? qSplitBy(tempId + "F", EntityType.BODY, false)
                        : fcpSideTrue;
                    tipSpanBodies = append(tipSpanBodies, tipPieceQ);

                    if (crossesAcp)
                    {
                        // Edge also spans ACP: split the RSL+tail piece further.
                        opSplitPart(context, tempId + "A", {
                                    "targets" : rslTailPieceQ,
                                    "tool" : qCreatedBy(id + "acpPlane", EntityType.FACE)
                                });
                        var acpSideTrueFA = qSplitBy(tempId + "A", EntityType.BODY, true);
                        var acpSideTrueBoxFA = evBox3d(context, { "topology" : acpSideTrueFA, "tight" : true });
                        var rslPieceQ = acpSideTrueBoxFA.maxCorner[0] < acpX + spanTol
                            ? acpSideTrueFA
                            : qSplitBy(tempId + "A", EntityType.BODY, false);
                        var tailPieceQ = acpSideTrueBoxFA.maxCorner[0] < acpX + spanTol
                            ? qSplitBy(tempId + "A", EntityType.BODY, false)
                            : acpSideTrueFA;
                        rslSpanBodies = append(rslSpanBodies, rslPieceQ);
                        tailSpanBodies = append(tailSpanBodies, tailPieceQ);
                    }
                    else
                    {
                        rslSpanBodies = append(rslSpanBodies, rslTailPieceQ);
                    }
                }
                else
                {
                    // Spans ACP only
                    opSplitPart(context, tempId + "A", {
                                "targets" : qCreatedBy(tempId, EntityType.BODY),
                                "tool" : qCreatedBy(id + "acpPlane", EntityType.FACE)
                            });
                    var acpSideTrueA = qSplitBy(tempId + "A", EntityType.BODY, true);
                    var acpSideTrueBoxA = evBox3d(context, { "topology" : acpSideTrueA, "tight" : true });
                    var rslPieceQ = acpSideTrueBoxA.maxCorner[0] < acpX + spanTol
                        ? acpSideTrueA
                        : qSplitBy(tempId + "A", EntityType.BODY, false);
                    var tailPieceQ = acpSideTrueBoxA.maxCorner[0] < acpX + spanTol
                        ? qSplitBy(tempId + "A", EntityType.BODY, false)
                        : acpSideTrueA;
                    rslSpanBodies = append(rslSpanBodies, rslPieceQ);
                    tailSpanBodies = append(tailSpanBodies, tailPieceQ);
                }
            }
        }

        //5. Extract wires for each batch of non-spanning edges
        if (size(tipEdgesArr) > 0)
            opExtractWires(context, id + "tipWire", { "edges" : qUnion(tipEdgesArr) });
        if (size(rslEdgesArr) > 0)
            opExtractWires(context, id + "rslWire", { "edges" : qUnion(rslEdgesArr) });
        if (size(tailEdgesArr) > 0)
            opExtractWires(context, id + "tailWire", { "edges" : qUnion(tailEdgesArr) });

        //6. Build combined body query arrays per region
        var tipBodyParts = tipSpanBodies;
        if (size(tipEdgesArr) > 0)
            tipBodyParts = append(tipBodyParts, qCreatedBy(id + "tipWire", EntityType.BODY));

        var rslBodyParts = rslSpanBodies;
        if (size(rslEdgesArr) > 0)
            rslBodyParts = append(rslBodyParts, qCreatedBy(id + "rslWire", EntityType.BODY));

        var tailBodyParts = tailSpanBodies;
        if (size(tailEdgesArr) > 0)
            tailBodyParts = append(tailBodyParts, qCreatedBy(id + "tailWire", EntityType.BODY));

        var hasTip = size(tipBodyParts) > 0;
        var hasRSL = size(rslBodyParts) > 0;
        var hasTail = size(tailBodyParts) > 0;

        //7. Label and sample each region
        var tipPoints = [];
        if (hasTip)
        {
            var tipWireQ = qUnion(tipBodyParts);
            setProperty(context, {
                        "entities" : tipWireQ,
                        "propertyType" : PropertyType.NAME,
                        "value" : "Tip Curve"
                    });
            tipPoints = genPointArray(context, id, tipWireQ, 'TIP', definition.tipCount, definition.includePoints, fcpORGIN, false, definition.sketchPoints, 'Tip_Sketch');
            if (definition.flipTip)
                tipPoints = reverse(tipPoints);
        }

        var rslPoints = [];
        if (hasRSL)
        {
            var rslWireQ = qUnion(rslBodyParts);
            setProperty(context, {
                        "entities" : rslWireQ,
                        "propertyType" : PropertyType.NAME,
                        "value" : "RSL Curve"
                    });
            rslPoints = genPointArray(context, id, rslWireQ, 'RSL', definition.rslCount, definition.includePoints, mrsORIGIN, false, definition.sketchPoints, 'RSL_Sketch');
            if (definition.flipRSL)
                rslPoints = reverse(rslPoints);
        }

        var tailPoints = [];
        if (hasTail)
        {
            var tailWireQ = qUnion(tailBodyParts);
            setProperty(context, {
                        "entities" : tailWireQ,
                        "propertyType" : PropertyType.NAME,
                        "value" : "Tail Curve"
                    });
            tailPoints = genPointArray(context, id, tailWireQ, 'TAIL', definition.tailCount, definition.includePoints, acpORIGIN, false, definition.sketchPoints, 'Tail_Sketch');
            if (definition.flipTail)
                tailPoints = reverse(tailPoints);
        }

        //8. Store point arrays as attributes and visualize
        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tipEdgePoints",
                    "attribute" : tipPoints
                });
        for (var tpPt in tipPoints)
            addDebugPoint(context, tpPt + fcpORGIN, DebugColor.RED);

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "rslEdgePoints",
                    "attribute" : rslPoints
                });
        for (var tpPt in rslPoints)
            addDebugPoint(context, tpPt + mrsORIGIN, DebugColor.BLUE);

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tailEdgePoints",
                    "attribute" : tailPoints
                });
        for (var tpPt in tailPoints)
            addDebugPoint(context, tpPt + acpORIGIN, DebugColor.GREEN);

        if (!definition.retainPlanes)
        {
            opDeleteBodies(context, id + "deleteFCPPlane", {
                        "entities" : qCreatedBy(id + "fcpPlane", EntityType.BODY)
                    });
            opDeleteBodies(context, id + "deleteACPPlane", {
                        "entities" : qCreatedBy(id + "acpPlane", EntityType.BODY)
                    });
        }

        setAttribute(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tableFormat",
                    "attribute" : { 'tableUnits' : definition.tableUnits, 'cleanUnits' : definition.cleanUnits, 'sigFigs' : definition.sigFigs }
                });

        //9. Footprint analysis on the combined sidecut path
        try
        {
            var allBodyParts = concatenateArrays([tipBodyParts, rslBodyParts, tailBodyParts]);
            var allWireEdges = [];
            for (var bodyQ in allBodyParts)
                allWireEdges = append(allWireEdges, qOwnedByBody(bodyQ, EntityType.EDGE));
            var fptPath = constructPath(context, qUnion(allWireEdges));
            analyzeFootprint(context, id + 'getFootprintDataBody', fptPath, definition.rslQuery, definition.showCurvature);
        }
        catch
        {
            reportFeatureInfo(context, id, 'FOOTPRINT MUST BE CONTINUIOUS. NO FOOTPRINT DATA ANALYSIS. Cannot form a tangent path from selected edges');
        }

        //10. Optionally retain or delete extracted wire curves
        if (!definition.retainCurves)
        {
            var deleteBodyParts = concatenateArrays([tipBodyParts, rslBodyParts, tailBodyParts]);
            if (size(deleteBodyParts) > 0)
                opDeleteBodies(context, id + "deleteCurves", { "entities" : qUnion(deleteBodyParts) });
        }

    });

function genPointArray(context is Context, id is Id, targetCurve is Query, curveName is string, numPoints is number, includePoints is Query, refOrigin is Vector, reverseOrder is boolean, createSketch is boolean, sketchID is string)
{

    var lengthParams = range(0, 1, numPoints); // length increments along path to get points at.


    var edges = evaluateQuery(context, qOwnedByBody(targetCurve, EntityType.EDGE));

    addDebugEntities(context, qUnion(edges), DebugColor.CYAN);


    var edgePath = constructPath(context, qUnion(edges));


    var pathLines is array = evPathTangentLines(context, edgePath, lengthParams).tangentLines;
    var expPoints is array = [];
    for (var i = 0; i < size(pathLines); i += 1)
    {
        expPoints = append(expPoints, pathLines[i].origin - refOrigin);
    }

    //expPoints = sort(expPoints, function(a, b) {return (a[0] - b[0]);});
    if (reverseOrder)
    {
        expPoints = reverse(expPoints);
    }
    /*
       //println(curveName~' Points are:');
       for (var i = 0; i < size(expPoints); i += 1)
       {
       //println(expPoints[i][0].value*1000~', '~expPoints[i][1].value*1000);
       }
     */

    if (createSketch)
    {
        var fptSketch = newSketchOnPlane(context, id + ("sketch" ~ sketchID), {
                "sketchPlane" : plane(refOrigin, vector(0, 0, 1))
            });
        for (var i = 0; i < size(expPoints); i += 1)
        {
            skPoint(fptSketch, ("point" ~ i ~ sketchID), {
                        "position" : vector(expPoints[i][0], expPoints[i][1])
                    });
        }

        skSolve(fptSketch);

        /*
           setProperty(context, {
           "entities" : qOwnedByBody(fptSketch),
           "propertyType" : PropertyType.NAME,
           "value" : sketchID
           });
         */

    }

    return expPoints;
}


annotation { "Table Type Name" : "Footprint Points" }
export const fptPointTable = defineTable(function(context is Context, definition is map) returns TableArray
    precondition
    {
        // Define the parameters of the table type
    }
    {
        var columnDefinitions = [ //tableColumnDefinition("region", "Region"),
            tableColumnDefinition("x", "X - Value"),
            tableColumnDefinition("y", "Y - Value")
            //,tableColumnDefinition("z", "Z - Value")
        ];

        var tipRows = [];
        var rslRows = [];
        var tailRows = [];

        //1. Tip Points

        const tipPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "tipEdgePoints"
                });

        var tableFormat = getAttributes(context, {
                    "entities" : qOrigin(EntityType.BODY),
                    "name" : "tableFormat"
                })[0];

        //println(tableFormat);

        var scaleFactor = 1;
        var suffixStr = '';
        if (tableFormat.tableUnits == exportUnits.MILLIMETER)
        {
            scaleFactor = 1000;
            suffixStr = ' mm';
        }

        if (tableFormat.tableUnits == exportUnits.INCH)
        {
            scaleFactor = 1000 / 25.4;
            suffixStr = ' in';
        }
        if (tableFormat.tableUnits == exportUnits.CENTIMETER)
        {
            scaleFactor = 100;
            suffixStr = ' cm';
        }

        //println('TABLE SCALEFACTOR = ' ~ scaleFactor);
        //println('TABLE SUFFIX STR = ' ~ suffixStr);


        for (var pt in tipPoints)
        {
            tipRows = append(tipRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));

        }

        //2. RSL Points
        const rslPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "rslEdgePoints"
                });

        for (var pt in rslPoints)
        {
            rslRows = append(rslRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));
        }
        //3. Tail Points
        const tailPoints = getAttribute(context, {
                    "entity" : qOrigin(EntityType.BODY),
                    "name" : "tailEdgePoints"
                });

        for (var pt in tailPoints)
        {
            tailRows = append(tailRows, tableRow({ "x" : formatTableValue(context, pt[0], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits), "y" : formatTableValue(context, pt[1], scaleFactor, tableFormat.sigFigs, suffixStr, tableFormat.cleanUnits) }));
        }


        // Compute the table



        return tableArray([table("TIP Points", columnDefinitions, tipRows), table("RSL Points", columnDefinitions, rslRows), table("TAIL points", columnDefinitions, tailRows)]);
    });

export function splitStr(splitStr is string, splitChar is string) returns array
{
    var retArray = [];
    var regexp = ".*" ~ splitChar ~ ".*";
    var stringArray = splitIntoCharacters(splitStr);
    var iterString is string = '';

    for (var i = 0; i < size(stringArray); i += 1)
    {
        if (!match(stringArray[i], regexp).hasMatch)
        {
            iterString = iterString ~ stringArray[i];

            if (i == size(stringArray) - 1)
            {
                retArray = append(retArray, iterString);
            }
        }
        else
        {
            retArray = append(retArray, iterString);
            iterString = '';
        }

    }

    return retArray;
}

export function formatTableValue(context is Context, val is ValueWithUnits, scaleFactor is number, sigFigs is number, suffixStr is string, cleanUnits is boolean)
{
    if (cleanUnits)
    {
        return roundToPrecision(val.value * scaleFactor, sigFigs);
    }
    else if (!cleanUnits)
    {
        return roundToPrecision(val.value * scaleFactor, sigFigs) ~ suffixStr;
    }
}